### PR TITLE
po-docgen: fix doc generation for inlined fields

### PR DESCRIPTION
**Pull request by dgrisonnet**
When po-docgen was generating the API documentation, it was
intentionally skipping inlined fields. Thus, they were absent from the
documentation instead of being displayed inline.
The assumption to skip inlined fields was correct for foreign types as
we most likely don't want their content to be part of the API
documentation. However, we want the content of internal types to be
inlined correctly.

This PR originates from the following discussion: https://github.com/prometheus-operator/prometheus-operator/pull/3370#discussion_r486931129

### CODE REVIEW

**Comment by dgrisonnet** [comment]
On top of my other PR, we get the following document: [api.md](https://github.com/prometheus-operator/prometheus-operator/compare/master...dgrisonnet:inlined-field-doc-example#diff-b1a95f484fe1197853692d47abbfe919)

**Review by paulfantom — APPROVED** [review]
lgtm

**Review by lilic — APPROVED** [review]
lgtm

Just one question, we had nothing inlined that was internal only external parts hence no changes to the api.md file, correct?

**Comment by dgrisonnet** [comment]
> Just one question, we had nothing inlined that was internal only external parts hence no changes to the api.md file, correct?

Correct, we only had external metav1.TypeMeta fields inlined.

**Pull request merged**
