### PR TITLE
Add PagerdutyURL to AlertmanagerGlobalConfig

### PR DESCRIPTION
**Pull request by mcbenjemaa**
## Description

Add PagerdutyURL to AlertmanagerGlobalConfig

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [X] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Adds  `spec.alertmanagerConfiguration.global.PagerdutyURL`  to the `Alertmanager` CRD
```

### CODE REVIEW

**Comment by mcbenjemaa** [comment]
@simonpasquier

**Comment by mcbenjemaa** [comment]
has been changed to plain string

**Review by ArthurSens — APPROVED** [review]
Sorry for taking this long to review, LGTM!

**Review by JoaoBraveCoding — APPROVED** [review]
lgtm

**Comment by rgarcia89** [comment]
Does not work for me. Has this been tested before?

```
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  ```

Name of the AlertmanagerConfig `alertmanager-self`.
Part of the Alertmanager manifest
```
  alertmanagerConfiguration:
    global:
      pagerdutyUrl: https://events.eu.pagerduty.com/generic/2010-04-15/create_event.json
    name: alertmanager-self
```

**Pull request merged**
