### PR TITLE
more docs on some API-fields

### PR DESCRIPTION
**Pull request by Dominik-K**
1. Explains some API-fields of the `ServiceMonitor` in more detail. From questions I had on these.
2. Quick-jump reference to Prometheus' alert & recording rules doc. Makes it also clear that they're 1:1 the Prometheus-API.
3. Explicitly mentioning the interval's default times should resolve an older discussion in https://github.com/prometheus-operator/prometheus-operator/pull/3308.

### CODE REVIEW

**Comment by brancz** [comment]
Awesome! Thank you for the contribution! This looks great to me. You're just going to have to run `make clean generate` and commit the changes to this PR, then CI should go green.

**Comment by Dominik-K** [comment]
@brancz Done. Hope it gets green.

**Comment by brancz** [comment]
Looks like docs didn't get re-generated correctly. Maybe try `make clean generate --always-make`.

**Comment by Dominik-K** [comment]
@brancz May you take this PR & fix the ongoing doc-generation errors, please?

How about automatically generating them via CI & push the output to another generated-only repo? It would invite external, low-volume contributors like me :-)
(TBH, I'm getting disappointed about how often I should re-trigger a build which could be automated away.)

**Comment by Dominik-K** [comment]
@paulfantom Thanks for reminding me finishing this PR (with your follow-PR #4077). I took the chance to understand the issue more. So hopefully now the CI gets green. 

BUT: Now the workflows need approval. May you trigger it, please?

**Comment by Dominik-K** [comment]
Still `generate` creates differences to my local one. I don't see the diff in the `ignoreNamespaceSelectors`, though. @paulfantom You?

**Comment by Dominik-K** [comment]
@paulfantom Can you approve the workflows again, please? The `generate`-issue should be fixed now 🤞

**Comment by paulfantom** [comment]
Thanks! :+1: 

Closes #4077

**Pull request merged**
