### PR TITLE
Add CRD category

### LINKED ISSUE #3842: Add category to CRDs
**What is missing?**

CRDs are not grouped together in category reducing discovery of CRs

**Why do we need it?**

To improve UX.

Using `kubectl get prometheus-operator` which would list all CRs belonging to prometheus-operator would be a nice improvement. It would be also nice to add another category like `monitors` which would group all `ServiceMonitor`, `PodMonitor`, and `Probe` objects.

**Environment**

* Prometheus Operator version: all

**Anything else we need to know?**:

This is easy to implement by assigning `.spec.categories` in CRDs definitions. More in https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#categories

### PR DESCRIPTION
**Pull request by paulfantom**
Resolves #3842

Creating PR before I forget how to implement it :smile: 

**Release Note Template (will be copied)**

```release-note:enhancement
CRDs are now part of prometheus-operator group allowing `kubectl get prometheus-operator` operation
```

### CODE REVIEW

**Comment by paulfantom** [comment]
Output of `kubectl get prometheus-operator` from [one of my clusters](https://github.com/thaum-xyz/ankhmorpork) after using CRDs from this PR:

```
k get prometheus-operator
NAME                                                    AGE
podmonitor.monitoring.coreos.com/kube-events-exporter   185d

NAME                                      VERSION   REPLICAS   AGE
alertmanager.monitoring.coreos.com/main   0.21.0    3          218d

NAME                                   VERSION   REPLICAS   AGE
prometheus.monitoring.coreos.com/k8s   2.24.0    2          80d

NAME                                                       AGE
servicemonitor.monitoring.coreos.com/kubelet               218d
servicemonitor.monitoring.coreos.com/prometheus            218d
servicemonitor.monitoring.coreos.com/coredns               218d
servicemonitor.monitoring.coreos.com/alertmanager          218d
servicemonitor.monitoring.coreos.com/grafana               218d
servicemonitor.monitoring.coreos.com/kube-state-metrics    218d
servicemonitor.monitoring.coreos.com/blackbox-exporter     5d
servicemonitor.monitoring.coreos.com/prometheus-operator   218d
servicemonitor.monitoring.coreos.com/pushgateway           218d
servicemonitor.monitoring.coreos.com/smokeping             218d

NAME                                          AGE
probe.monitoring.coreos.com/ankhmorpork       124d
probe.monitoring.coreos.com/prometheus-demo   124d
probe.monitoring.coreos.com/thaum-sites       57d
```

**Comment by brancz** [comment]
Super cool. I love it!

**Comment by brancz** [comment]
Any reason not to merge this?

**Comment by paulfantom** [comment]
No, just people locked in a long streak of f2f meetings :)

**Comment by juliantaylor** [comment]
prometheusrules is missing the category

**Comment by paulfantom** [comment]
@juliantaylor great finding! Could you create a PR with a fix?

**Pull request merged**
