### PR TITLE
Update push-docker-image.sh to support ppc64le architecture

### PR DESCRIPTION
**Pull request by amintek**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Adding support for ppc64le architecture

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

adding support for ppc64le architecture

```release-note

```

### CODE REVIEW

**Review by PhilipGough — APPROVED** [review]
/lgtm

**Comment by amintek** [comment]
> 
> 
> lgtm - @amintek, can you add a message to the changelog entry above.

done

**Comment by amintek** [comment]
Any update ?

**Comment by PhilipGough** [comment]
Fixes #4258

**Pull request merged**
