### PR TITLE
feat(remote): add support prometheus remote write/read ProxyConfig 

### PR DESCRIPTION
**Pull request by dongjiang1989**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

add support prometheus remote write/read ProxyConfig 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
add support prometheus remote write/read ProxyConfig 
```

### CODE REVIEW

**Comment by simonpasquier** [comment]
Thanks for looking into it! It'd be better to fix https://github.com/prometheus-operator/prometheus-operator/issues/6523 first. It would be super dope if you tackle first :)

**Comment by dongjiang1989** [comment]
> Thanks for looking into it! It'd be better to fix #6523 first. It would be super dope if you tackle first :)

Got it. I'll add a PR to fix it.

**Comment by slashpai** [comment]
> > Thanks for looking into it! It'd be better to fix #6523 first. It would be super dope if you tackle first :)
> 
> Got it. I'll add a PR to fix it.

Thank you. Could you please create the PR to release-0.73 branch so we can include the fix in patch release?
https://github.com/prometheus-operator/prometheus-operator/pull/6527

**Comment by dongjiang1989** [comment]
> > > Thanks for looking into it! It'd be better to fix #6523 first. It would be super dope if you tackle first :)
> > 
> > 
> > Got it. I'll add a PR to fix it.
> 
> Thank you. Could you please create the PR to release-0.73 branch so we can include the fix in patch release? #6527

Got it

**Comment by dongjiang1989** [comment]
@simonpasquier  https://github.com/prometheus-operator/prometheus-operator/pull/6541 have been merged.
PTAL.

**Comment by dongjiang1989** [comment]
> Thanks for looking into it! It'd be better to fix #6523 first. It would be super dope if you tackle first :)

Please re-check it. Thanks.

**Comment by simonpasquier** [comment]
Thanks for revisiting the PR! With the latest changes to pkg/assets, I suggest to load the referenced secrets referenced by the proxy config in `AddRemoteWritesToStore()` and `AddRemoteReadsToStore()`. Then you wouldn't need to pass the context to generateRemoteWriteConfig().

**Comment by dongjiang1989** [comment]
> Thanks for revisiting the PR! With the latest changes to pkg/assets, I suggest to load the referenced secrets referenced by the proxy config in `AddRemoteWritesToStore()` and `AddRemoteReadsToStore()`. Then you wouldn't need to pass the context to generateRemoteWriteConfig().

Thanks @simonpasquier 
Add the referenced secrets referenced by the proxy config in `AddRemoteWritesToStore()` and `AddRemoteReadsToStore()`. 
also remove `generateRemoteWriteConfig()` context  and `addProxyConfigtoYaml()` context.

**Comment by dongjiang1989** [comment]
@simonpasquier Please re-check it, thanks

**Review by simonpasquier — APPROVED** [review]
Thanks!

**Pull request merged**
