### PR TITLE
feat(xds): Add support eureka service discovery to the ScrapeConfig CRD 

### PR DESCRIPTION
**Pull request by dongjiang1989**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Add support eureka service discovery to the ScrapeConfig CRD 
ref: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#eureka_sd_config

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Add support eureka service discovery to the ScrapeConfig CRD 
```

### CODE REVIEW

**Comment by dongjiang1989** [comment]
@slashpai  PTAL, thanks

**Comment by slashpai** [comment]
You would need to rebase since https://github.com/prometheus-operator/prometheus-operator/pull/6401 is merged

**Comment by dongjiang1989** [comment]
> You would need to rebase since #6401 is merged

Thanks. @slashpai  git rebase done. 

first #6408 merge, then rebase #6327.

**Comment by slashpai** [comment]
For a future reference,  to pulling upstream changes `git pull upstream main --rebase` is better than merge strategy to have better commit history otherwise merge commits show up (example merge commits like  `Merge branch 'main' into add-eureka-sd'`)  :)

**Comment by dongjiang1989** [comment]
> For a future reference, to pulling upstream changes `git pull upstream main --rebase` is better than merge strategy to have better commit history otherwise merge commits show up (example merge commits like `Merge branch 'main' into add-eureka-sd'`) :)

Hmmm... I agree with your opinion. In this PR, Maybe squash and merge is better. Among the 5 commits, the core is the first commit.

**Review by slashpai — APPROVED** [review]

**Pull request merged**
