### PR TITLE
prometheus: add ready_timeout flag to Thanos sidecar

### LINKED ISSUE #3275: Support --prometheus.ready_timeout flag for thanos-sidecar
**What is missing?**

The `--prometheus.ready_timeout` flag for thanos-sidecar

**Why do we need it?**

The sidecar crashes if prometheus is not ready in 10 minutes, so we want to increase it as our prometheus is fairly big

**Prometheus Operator version:**

`8.14.0`

### PR DESCRIPTION
**Pull request by PhilipGough**
This change adds additional config to Thanos sidecar to increase/decrease the max wait time for Prometheus and Fixes #3275

**Release Note Template (will be copied)**

```release-note:REPLACEME
Adds configuration to set the Prometheus ready timeout to Thanos sidecar 
```

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by simonpasquier** [comment]
for some reason `Documentation/api.md` wasn't regenerated. Can you try running `make Documentation/api.md` and committing the changes (though I think that `make generate` should handle it?

**Comment by simonpasquier** [comment]
lgtm

**Comment by PhilipGough** [comment]
> for some reason `Documentation/api.md` wasn't regenerated. Can you try running `make Documentation/api.md` and committing the changes (though I think that `make generate` should handle it?

Yeah it should, I ran the make target manually and it output the `Documentation/*` paths so not sure why it wasn't generated originally

**Comment by simonpasquier** [comment]
Thanks and congrats for your first PR!

**Pull request merged**
