### PR TITLE
*: cut v0.47.0

### PR DESCRIPTION
**Pull request by simonpasquier**
Do not merge for now, I need to investigate why CI has become flaky on the last runs...

**Release Note Template (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by paulfantom — APPROVED** [review]
lgtm on green

**Comment by simonpasquier** [comment]
The first commit of the PR reverts #3933. I've executed the tests three times (2 runs passed, the third run is in progress as I write this comment) and the CI failures that we've been experiencing recently seem to be gone.

**Comment by paulfantom** [comment]
LGTM. Let's open an issue to bring back #3933 in an improved version and potentially increase test coverage and robustness so this won't be manifested in flakes.

**Comment by simonpasquier** [comment]
> Let's open an issue to bring back #3933 in an improved version

https://github.com/prometheus-operator/prometheus-operator/issues/3980

**Comment by metalmatze** [comment]
I've updated the website which isn't currently pulling down the version automatically. Or it never will? 
Maybe updating our release process is enough to not forget?
https://github.com/prometheus-operator/website/commit/b012633cc4de10fc58db9341eabeb57a2319e9bf

**Comment by simonpasquier** [comment]
I'll push an update to the release doc.

**Comment by simonpasquier** [comment]
https://github.com/prometheus-operator/prometheus-operator/pull/3983

**Pull request merged**
