### PR TITLE
replace the List with a set of Get's

### PR DESCRIPTION
**Pull request by gitgaoxiang**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._
https://github.com/prometheus-operator/prometheus-operator/issues/4968

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
change secret list to get , Resolve the pressure on Apiserver when NS secret are too many
```

### CODE REVIEW

**Comment by JoaoBraveCoding** [comment]
LGTM 👍 but a maintainer has to review it!
Thank you for the contribution 🥇

**Comment by fpetkovski** [comment]
I am not sure if this reduces the load on the API server, since a `List` request should be going to the cache, while a `Get` request would often go directly to API server.

**Comment by PhilipGough** [comment]
Agree with @fpetkovski and I don't think we could blindly merge this without some metrics or benchmarks to show an improvement.

IIUC, the issue stems from you deploying your monitoring components in the same namespace as your other workloads!

**Comment by gitgaoxiang** [comment]
@PhilipGough We do create other services under the monitor ns, because resources in ns change frequently, the operator requests the apiserver frequently. this leads to insufficient memory.  However,can we optimizing list perform scene，request only when additional is configured. I submit merge for this.

**Pull request closed without merging**
