### PR TITLE
gomod: adjust module path to new home

### LINKED ISSUE #3393: 0.41 release still references old home of prometheus-operator in go.mod
https://github.com/prometheus-operator/prometheus-operator/blob/f194e0349816f4ad18ab1d443ef47c424e7b6c40/go.mod#L1

leading to errors like

```$ go get github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1
go: found github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1 in github.com/prometheus-operator/prometheus-operator v0.41.0
go get: github.com/prometheus-operator/prometheus-operator@v0.41.0: parsing go.mod:
        module declares its path as: github.com/coreos/prometheus-operator
                but was required as: github.com/prometheus-operator/prometheus-operator```

### PR DESCRIPTION
**Pull request by RiRa12621**
this fixes #3393

### CODE REVIEW

**Comment by metalmatze** [comment]
Hm. For older release I feel like the go mod replace might what you want. Not sure why this is happening in the first place though.

**Comment by RiRa12621** [comment]
This is happening on a fresh project and therefore I think the default to pull is latest release, which is 0.41, which has that issue.

For the record: this can me motivated by pinning the import to a commit on master

**Comment by lilic** [comment]
Thanks! Can you run go mod tidy, that might fix it?

**Comment by simonpasquier** [comment]
It's a bit unfortunate but it will go away once we have v0.42.0 available. I think that for the time being, importing `github.com/coreos/prometheus-operator` is a reasonable workaround.

**Comment by RiRa12621** [comment]
Yeah i agree @simonpasquier 

so for the time being, pinning is not pretty but mitigates the problem until 0.42 is released

@lilic i'll try but i have to "un-import" it first and then try again

**Pull request closed without merging**
