### PR TITLE
fix: Invalid child routes in AlertmanagerConfig CRD triggers a panic …

### PR DESCRIPTION
**Pull request by yp969803**
…(#6277)

## Description
fixes: #6277 
Invalid child routes in AlertmanagerConfig CRD triggers a panic, despise panic returning the err for invalid child routes

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification
make test

## Changelog entry

```
Returning err for invalid child routes

```

### CODE REVIEW

**Comment by yp969803** [comment]
@slashpai can you review this pr

**Comment by simonpasquier** [comment]
We'd need a reproducer to understand why the issue happens in the first place. But the fix might be that we should unmarshal the child routes with strict mode.

https://github.com/prometheus-operator/prometheus-operator/blob/578e0c32d7db1a24a6c6adaaed7bec62e1b3c11e/pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go#L139-L150

https://github.com/prometheus-operator/prometheus-operator/blob/578e0c32d7db1a24a6c6adaaed7bec62e1b3c11e/pkg/apis/monitoring/v1beta1/alertmanager_config_types.go#L138-L149

**Comment by yp969803** [comment]
@simonpasquier added the strict mode

**Comment by simonpasquier** [comment]
> @simonpasquier added the strict mode

I don't see this in the current PR.
As I said before, we need a reproducer + test first before digging into the fix.

**Pull request closed without merging**
