### PR TITLE
Refactoring CI pipelines

### PR DESCRIPTION
**Pull request by paulfantom**
Solving few problems at once:

- Fixing 50min timeout on travis by moving to GH actions which have 6h timeout.
- Adding build and generation tests on MacOS to prevent issues we had in the past where Makefile was broken on this OS.
- Switching to kind (closing https://github.com/prometheus-operator/prometheus-operator/pull/2785). In the past it was not possible due to frequent lack of images for k8s in kind. Lately Kind publishes images for all k8s versions.
- Removing bash scripts necessary for making minikube work on travis

### CODE REVIEW

**Comment by paulfantom** [comment]
Since GH actions are not on `master` branch, this won't run here. CI results can be seen in my fork at https://github.com/paulfantom/prometheus-operator/actions

**Comment by s-urbaniak** [comment]
LGTM :+1:

**Comment by lilic** [comment]
@paulfantom Nice work! One thing the unit tests and other checks don't seem to show up in your fork? Or I might be missing it? https://github.com/paulfantom/prometheus-operator/actions/runs/243309367

**Comment by paulfantom** [comment]
They do, but not in e2e workflow. You can see them in `tests` workflow: https://github.com/paulfantom/prometheus-operator/actions/runs/243309366

Possibly both workflows will be unified into one file due to some shortcomings of github actions.

**Comment by paulfantom** [comment]
This is finished. I tested everything in https://github.com/paulfantom/prometheus-operator/actions/runs/244944814 and it looks good.

Required Travis CI check will need to be overridden as travis configuration is removed.

**Comment by simonpasquier** [comment]
Awesome! LGTM

**Comment by lilic** [comment]
Nice, lgtm! 👍  I would say lets hold off on this for merging until tomorrow, until the release, just in case we run into any problems.

**Pull request merged**
