### PR TITLE
Refactor to remove context.TODO

### PR DESCRIPTION
**Pull request by arghya88**
Ref #3158

### CODE REVIEW

**Comment by s-urbaniak** [comment]
Thank you a lot for the contribution! This lgtm, but I believe we have a couple more occurences in `pkg/alertmanager/operator.go`. Do you mind to address these too?

**Comment by arghya88** [comment]
> Thank you a lot for the contribution! This lgtm, but I believe we have a couple more occurences in `pkg/alertmanager/operator.go`. Do you mind to address these too?

Done

**Comment by s-urbaniak** [comment]
LGTM on green, thank you! :tada:

**Comment by lilic** [comment]
Thanks for the PR!! 🎉

**Pull request merged**
