### PR TITLE
Add Email Receiver type to AlertmanagerConfig CRD

### LINKED ISSUE #3533: Add Email Receiver type to AlertmanagerConfig CRD
**What is missing?**

In #3451 we added the AlertmanagerConfig CRD, with just the PagerDuty receiver type, meaning that alert notifications can only be routed to PagerDuty. Alertmanager supports several other Receiver types, with this being one (other issues will be created for the others).

**Why do we need it?**

We should be able to define all of the Alertmanager receivers in AlertmanagerConfig CRs.

**Anything else we need to know?**:

The proposal for AlertmanagerConfig CRD is [here](https://docs.google.com/document/d/1aVVttvocop8zNezwrNFbHh_HKRW_fhJUZqhmrr8fGK0/edit#heading=h.5ua2yyj2xm4h), and it includes some information on this receiver type.

The Alertmanager config docs [here](https://prometheus.io/docs/alerting/latest/configuration/) show how this receiver is expected to be in the resulting Alertmanager config.

### PR DESCRIPTION
**Pull request by sev3ryn**
fixes #3533

### CODE REVIEW

**Comment by sev3ryn** [comment]
@simonpasquier @lilic PR is ready to be reviewed. 
Before merging it waits for #3691 to be merged to master, so I can rebase on top of it

**Comment by sev3ryn** [comment]
@grdryn , last alertmanager CRD to review :)

**Review by simonpasquier — COMMENTED** [review]
lgtm but it needs a rebase

**Comment by sev3ryn** [comment]
@simonpasquier rebase done

**Review by lilic — APPROVED** [review]
Thanks!! 🎉

**Pull request merged**
