### PR TITLE
feat: optimize []string annotation

### PR DESCRIPTION
**Pull request by dongjiang1989**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

optimize []string kubebuilder annotation

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
NONE
```

### CODE REVIEW

**Comment by dongjiang1989** [comment]
> Thanks for the PR! We can't change validations on v1 APIs unfortunately (at least not being stricter as it could break users). I'd also be reluctant to change v1beta1 APIs and v1alpha1 AlertmanagerConfig is frozen. Which basically leaves us with the v1alpha1 ScrapeConfig CRD.
> 
> We'd need e2e tests too for each added validation.
> 
> cc @mviswanathsai

Thanks. @simonpasquier 
I Got it.  I'll change it and add e2e test cases.

**Comment by nicolastakashi** [comment]
Thanks for taking it @dongjiang1989 I think it's not a ENHANCEMENT i think it's a NONE on the change log, wdyt @simonpasquier ?

**Comment by dongjiang1989** [comment]
> Thanks for taking it @dongjiang1989 I think it's not a ENHANCEMENT i think it's a NONE on the change log, wdyt @simonpasquier ?

Thanks @nicolastakashi  Got it. Change it done.

**Review by simonpasquier — APPROVED** [review]
Thanks! Technically it's a CHANGE since we're hardening the API validations.

**Pull request merged**
