### PR TITLE
Parameterize sharding key(s)

### PR DESCRIPTION
**Pull request by hooten**
Currently it is only possible to shard by `__address__`. This PR allows the user to specify `shardingLabels` in the  `Prometheus` CR. This is a useful enhancement for users who would like a different sharding strategy (e.g., by `tenant`, `namespace`, or some other common label that exists in their organizations).

```
release-note:enhancement
```

### CODE REVIEW

**Comment by s-urbaniak** [comment]
Thank you for the contribution!

I had the same question initially when the feature was introduced and I think __address__ was chosen very consciously as per https://github.com/prometheus-operator/prometheus-operator/pull/3241#issuecomment-685733880.

I believe the direction we want to head is to work on more elaborated sharding mechanisms to prevent resharding as much as possible, but @brancz can shed more light here I guess.

**Comment by brancz** [comment]
I don't really see how distribution is intended to change with more labels. Could you give the actual example you intend to use this for and what effect you expect it to have?

**Comment by hooten** [comment]
Originally, the thought was to shard by tenant, so that the tenant data could be collocated inside a single prometheus pod for alert evaluation. But thinking about it more, that would require some other mechanism to distribute the data uniformly. 

Thanks for the feedback! Closing the PR.

**Comment by hooten** [comment]
Would using a Thanos ruler be a way to get around this problem?

**Comment by brancz** [comment]
If you start distributing data across shards, then yes you will always need something like Thanos to query everything globally.

**Comment by nicolastakashi** [comment]
Hi @brancz!

Sorry to reactive this topic hehe!

But let's imagine that I want to have shards by functionality such as:

- 3 Prometheus Instances Scrapping ElasticSearch
- 2 Prometheus Instances Scrapping MongoDB

How I can ensure that only one shard will be scrape the Elastic and will not scrape the MongoDB?

**Comment by paulfantom** [comment]
> How I can ensure that only one shard will be scrape the Elastic and will not scrape the MongoDB?

That might be easier to achieve by having separate `Prometheus` (separate CRs) for each functionality.

**Comment by nicolastakashi** [comment]
Do you mean to have different releases of Prometheus Operator?

**Comment by paulfantom** [comment]
No, two different `Prometheus` CRs.

**Comment by nicolastakashi** [comment]
Hmm!
I don't know if I got it, there is any example that you can share with me?

**Comment by paulfantom** [comment]
I don't have anything at hand. What I mean is to have following objects:

Prometheus responsible for mongodb
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: mongo
  name: mongo
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  image: quay.io/prometheus/prometheus:v2.26.0
  replicas: 2
  resources:
    limits:
      cpu: "1"
    requests:
      cpu: 140m
      memory: 1900Mi
  retention: 7d
  ruleNamespaceSelector: {}
  ruleSelector: # Use selector to restrict which PrometheusRules should go into this prom
  serviceAccountName: prometheus-monogo
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: # Use selector to restrict which ServiceMonitors should go into this prom
  version: 2.26.0
```

Prometheus responsible for ElasticSearch
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: es
  name: es
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  image: quay.io/prometheus/prometheus:v2.26.0
  replicas: 2
  resources:
    limits:
      cpu: "1"
    requests:
      cpu: 140m
      memory: 1900Mi
  retention: 7d
  ruleNamespaceSelector: {}
  ruleSelector: # Use selector to restrict which PrometheusRules should go into this prom
  serviceAccountName: prometheus-es
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: # Use selector to restrict which ServiceMonitors should go into this prom
  version: 2.26.0
```

One prometheus-operator can manage multiple prometheus servers :)

**Comment by nicolastakashi** [comment]
Awesome, thank you sou much 😄

**Pull request closed without merging**
