### PR TITLE
Backport PR #3233

### PR DESCRIPTION
**Pull request by benjaminhuo**
Backport PR #3233

### CODE REVIEW

**Comment by lilic** [comment]
This is a feature, not a bugfix it was marked in the original issue as such with a label, I would not backport this one https://github.com/coreos/prometheus-operator/issues/3196 cc @brancz

**Comment by benjaminhuo** [comment]
Actually the original alertmanager issue https://github.com/prometheus/alertmanager/issues/1814 is marked as a bug

**Comment by lilic** [comment]
@simonpasquier can you chime in, would this be a bug worth backporting?

**Comment by simonpasquier** [comment]
I'm ok with backporting this though it could be against release-0.41. Not sure why #3196 was tagged as a feature TBH.

**Comment by simonpasquier** [comment]
#3233 has been backported to `release-0.38` thanks to #3300. We [agreed](https://github.com/prometheus-operator/prometheus-operator/pull/3300#issuecomment-678301382) that the 0.38 branch is worth maintaining for some time because it's the last release to support Kubernetes <= 1.15. We also said that maintaining every release branch isn't sustainable so I'm closing this PR.

**Comment by benjaminhuo** [comment]
Agree, I should close this PR long time ago...

**Pull request closed without merging**
