### PR TITLE
.github,scripts: add promlinter to lint our metric names

### PR DESCRIPTION
**Pull request by paulfantom**
We could use this awesome tool to check if our metric names conform to Prometheus metric name best practices.

/cc @prometheus-operator/prometheus-operator-reviewers @yeya24

### CODE REVIEW

**Review by kakkoyun — APPROVED** [review]
LGTM 💯

**Comment by simonpasquier** [comment]
:+1: happy that it didn't found any offender :)

**Comment by yeya24** [comment]
Thanks! I am so happy to see that `promlinter` gets its first adopter :smile: 

But something I want to mention here, the tool is not very mature and it cannot detect all the metrics (Like some variables used when defining metrics) in the codebase. So if there is no problem reported by the tool, it doesn't mean we are 100% safe :( 

Like @bwplotka mentioned, might be good to also detect the metrics naming in the runtime (maybe E2E test) using `promtool` to ensure we are good.

**Review by bwplotka — APPROVED** [review]

**Comment by s-urbaniak** [comment]
LGTM too this is very nice!
@simonpasquier just needs a rebase.

**Comment by lilic** [comment]
You mean @paulfantom it needs a rebase ;)

Thanks lgtm! 🎉

**Comment by paulfantom** [comment]
Rebased

**Pull request merged**
