### PR TITLE
Support StatefulSet patching

### PR DESCRIPTION
**Pull request by heylongdacoder**
## Description

_Fixes #3488, Fixes #4298_

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Allow user to inject arbitrary fields into Alertmanager, ThanosRuler and Prometheus StatefulSet
```

### CODE REVIEW

**Comment by Grounz** [comment]
Hi, what's the status for this feature ?

**Comment by heylongdacoder** [comment]
@Grounz I think this PR wont be merge probably. You may check the whole discussion from this youtube [video](https://www.youtube.com/watch?v=PWliAmL_FJM) :)

**Comment by simonpasquier** [comment]
Hey! Sorry for the very late feedback but we've discussed https://github.com/prometheus-operator/prometheus-operator/issues/4691 at the last contributors office hours and we agreed that instead of exposing a way to patch the generated statefulset, we were ok adding support for `hostAlias` in the Prometheus, Alertmanager and ThanosRuler CRDs.
Do you want to tackle this? If yes, it's probably best to close this PR and open a new one.

**Comment by heylongdacoder** [comment]
alright, I will do it :)

**Pull request closed without merging**
