### PR TITLE
Create release v0.42.0 

### PR DESCRIPTION
**Pull request by metalmatze**
> The Answer to the Ultimate Question of Life, the Universe, and Everything is 42

Let me know if the changelog sounds about right.

---

Sorry, I need a new PR as I accidentally pushed to origin as `git fork` did this:
```
metalmatze      ssh://git@github.com/prometheus-operator/prometheus-operator.git (fetch)
metalmatze      ssh://git@github.com/prometheus-operator/prometheus-operator.git (push)
origin  git@github.com:prometheus-operator/prometheus-operator.git (fetch)
origin  git@github.com:prometheus-operator/prometheus-operator.git (push)
```
:sweat_smile: :100:

### CODE REVIEW

**Review by lilic — APPROVED** [review]
lgtm 👍

**Comment by s-urbaniak** [comment]
LGTM \o/

**Comment by brancz** [comment]
lgtm, nothing we can do about the timeout until the CI refactor @paulfantom is working on

**Review by simonpasquier — APPROVED** [review]
:+1:

**Comment by metalmatze** [comment]
Rebase to contain latest e2e tests from @paulfantom

**Comment by paulfantom** [comment]
LGTM on green.

**Pull request merged**
