### PR TITLE
Fix prom upgrade test

### PR DESCRIPTION
**Pull request by ArthurSens**
## Description

Fixing the test that I broke with #5732 😬 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [X] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Comment by ArthurSens** [comment]
The last commit needs to be dropped before merging

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by ArthurSens** [comment]
Hmmmm, still getting rate limited :/

I'll add an extra commit decreasing the frequency we check for ready status

**Comment by simonpasquier** [comment]
The `client rate limiter Wait returned an error: context deadline exceeded` message is a bit misleading: in fact, it tells that the wait function timed out without success.

**Comment by ArthurSens** [comment]
> The `client rate limiter Wait returned an error: context deadline exceeded` message is a bit misleading: in fact, it tells that the wait function timed out without success.

Thanks for the pointer! Indeed the message got me in the wrong direction

After some debugging I've realized that `t.Parallel()` in `testPromVersionMigration` would unblock the deferred function `testCtx.Cleanup(t)`. The cleanup deletes the prometheus-operator, therefore the Prometheus objects would never get reconciled.

Since this test suite only has one single test, I just removed t.Parallel() and now it is working :)

**Review by simonpasquier — APPROVED** [review]

**Pull request merged**
