### PR TITLE
replace goKitLogger in controller and namespace denylist

### PR DESCRIPTION
**Pull request by perebaj**
## Description

- Replace goKitLogger in controller and namespace denylist

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Review by perebaj — COMMENTED** [review]
The last one 🥳

The only place where we cannot remove is [this one](https://github.com/prometheus-operator/prometheus-operator/blob/main/cmd/prometheus-config-reloader/main.go#L129-L132)

Because some third libraries ([1](https://github.com/prometheus-operator/prometheus-operator/blob/main/cmd/prometheus-config-reloader/main.go#L184-L188) and [2](https://github.com/prometheus-operator/prometheus-operator/blob/main/cmd/prometheus-config-reloader/main.go#L206-L212)) are using the goKitLogger

**Review by simonpasquier — APPROVED** [review]
Thanks!

**Comment by ArthurSens** [comment]
> The only place where we cannot remove is [this one](https://github.com/prometheus-operator/prometheus-operator/blob/main/cmd/prometheus-config-reloader/main.go#L129-L132)
> 
> Because some third libraries ([1](https://github.com/prometheus-operator/prometheus-operator/blob/main/cmd/prometheus-config-reloader/main.go#L184-L188) and [2](https://github.com/prometheus-operator/prometheus-operator/blob/main/cmd/prometheus-config-reloader/main.go#L206-L212)) are using the goKitLogger

Oh damn, I was not expecting that. Ideally we would remove the go-kit dependency completely.

I can see that the third party libraries using this are all friends :), I'll open issues to their repo to try to get this done.
"github.com/prometheus/exporter-toolkit/web"
""github.com/thanos-io/thanos/pkg/reloader""

**Comment by ArthurSens** [comment]
Here you go:

https://github.com/prometheus/exporter-toolkit/issues/239
https://github.com/thanos-io/thanos/issues/7677

**Comment by ArthurSens** [comment]
exporter-toolkit switched to slog: https://github.com/prometheus/exporter-toolkit/releases/tag/v0.13.0

Only thanos' config reloader left :)

**Pull request merged**
