### PR TITLE
Fix image path in troubleshooting.md

### PR DESCRIPTION
**Pull request by pkprzekwas**
## Description

Fix path for the diagram linked in `troubleshooting.md`

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
- Fix `custom-metrics-elements.png` link in troubleshooting.md
```

### CODE REVIEW

**Comment by pkprzekwas** [comment]
Looks like CI failed. I checked an error and it seems the https://prometheus-operator.dev/docs/operator/troubleshooting/#overview-of-servicemonitor-tagging-and-related-elements renders the image properly.

**Comment by pkprzekwas** [comment]
> Maybe it's worth documenting in the code next to it.

Do you mean reverting the change and adding a comment?

**Comment by simonpasquier** [comment]
@metalmatze i've filed #5411 because we got one PR like this every week despite the comment saying that the "broken" image is expected on GitHub (not to blame you @pkprzekwas!).

**Comment by pkprzekwas** [comment]
@simonpasquier should we close this in that case?

**Comment by simonpasquier** [comment]
yes

**Pull request closed without merging**
