### PR TITLE
Update storage.md -> storage class api update

### PR DESCRIPTION
**Pull request by theadzik**
The API has changed.

storageclass.kubernetes.io/is-default-class should be used now:
https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#defaulting-behavior

**Release Note Template (will be copied)**

```release-note:REPLACEME

```

### CODE REVIEW

**Comment by fpetkovski** [comment]
lgtm

**Review by simonpasquier — COMMENTED** [review]
thanks!

**Comment by simonpasquier** [comment]
@theadzik you need to run `make generate` and commit the changes :)

**Comment by theadzik** [comment]
Not what I expected... /r and some non-changes. Sorry for the mess

**Comment by theadzik** [comment]
I made too much of a mess. WSL + `make generate` don't work well together.

**Comment by simonpasquier** [comment]
no worries, I'll cherry-pick your commit in #4171

**Pull request closed without merging**
