### PR TITLE
Change status conditions to follow conventions

### PR DESCRIPTION
**Pull request by thetechnick**
## Description

Currently prometheus-operator status conditions don't follow kubernetes
api conventions. This PR replaces the custom condition type with a
definition from kubernetes/apimachinery.

It also uses helper functions from apimachinery, where appropriately to
reduce code duplication.

This change is to be considered API breaking(!), dependent on release
management and consistency guarantees.

Follow up from #4975 

Signed-off-by: Nico Schieder <nschieder@redhat.com>

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [x] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
changed status conditions to be consistent with kubernetes api conventions
```

### CODE REVIEW

**Review by JoaoBraveCoding — APPROVED** [review]
LGTM 👍

**Comment by apahim** [comment]
@simonpasquier can you please take a look?

**Review by simonpasquier — COMMENTED** [review]
While I see where you're coming from, my first remark is that we can't change the actual API because the CRD version is v1. Having said that, I'm fine with adding things like `observedGeneration` and improving the API documentation.

**Comment by thetechnick** [comment]
Closing in favor of a follow up PR just containing observedGeneration to not break backwards compatibility.
Thanks everyone for having a look!

**Pull request closed without merging**
