### PR TITLE
alertmanager: Add follow_redirects and oauth fields to httpClientConfig

### PR DESCRIPTION
**Pull request by PhilipGough**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Close the drift between internal httpClientConfig and [the latest `HTTPClientConfig` from Prometheus ](https://github.com/prometheus/common/blob/00591a3ea9c0d18f6bc983818a23901d4154077f/config/http_config.go#L178-L199)

Add follow_redirects and support oauth config.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Support following redirects and Oauth2 in HTTP Client config in raw alertmanager config secret
```

### CODE REVIEW

**Comment by simonpasquier** [comment]
I suppose that you'll raise a follow-up PR for the AlertmanagerConfig CRD?

**Comment by PhilipGough** [comment]
> I suppose that you'll raise a follow-up PR for the AlertmanagerConfig CRD?

Yes, that is how we having been splitting these so far. That is of course assuming we want to include those in the CRD, but I had assumed yes and will follow up with it.

**Comment by simonpasquier** [comment]
lgtm

**Comment by simonpasquier** [comment]
i'm fine with another PR :)

**Pull request merged**
