### PR TITLE
Improve config generator logging

### PR DESCRIPTION
**Pull request by simonpasquier**
## Description

While reviewing https://github.com/prometheus-operator/prometheus-operator/pull/4563 I realized that when a configuration option wasn't supported for the given Prometheus version, the operator didn't log the issue in a very consistent way: it was not logged sometimes and even if logged, the message varied.

Once I started digging the rabbit hole, I included other changes to:
* simplify (IMHO) the structure of the codebase (mostly relying on the ConfigGenerator fields rather than passing around tons of parameters).
* clarify the API documentation for `OverrideHonorLabels` and `OverrideHonorTimestamps`.

There should be no functional change but the CI will tell.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Improved logging when the given Prometheus version doesn't support some of the CR fields.
```

### CODE REVIEW

**Comment by metalmatze** [comment]
Nice! :relaxed:

**Comment by fpetkovski** [comment]
Really nice work! Should we mark this as an enhancement?

**Review by PhilipGough — APPROVED** [review]
Nice clean up

lgtm

**Comment by simonpasquier** [comment]
@fpetkovski i've updated the PR description and will defer to the next release shepherd if it's worth a mention in the changelog :)
I'll wait for #4535 to merge first (otherwise it would create a merge conflict).

**Pull request merged**
