### PR TITLE
alertmanager: ensure alertmananger library is up to date

### PR DESCRIPTION
**Pull request by chrisdotm**
## Description

Attempting to resolve https://github.com/prometheus-operator/prometheus-operator/issues/4755. It seems the images that are being generated are using an old version of github.com/prometheus/alertmanager due to the replace.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

Don't downgrade the alertmanager library

```release-note
alertmanager library was being forced down to v0.23.0 while the api_key_file for opsgenie was introduced in v0.24.0
```

### CODE REVIEW

**Comment by PhilipGough** [comment]
The alertmanager lib has been at v0.24.0 as of ~2 months ago via https://github.com/prometheus-operator/prometheus-operator/commit/bf8476725f96395081ea24f72fb6b6fb8c29df92

**Comment by chrisdotm** [comment]
> The alertmanager lib is already at v0.24.0 via [bf84767](https://github.com/prometheus-operator/prometheus-operator/commit/bf8476725f96395081ea24f72fb6b6fb8c29df92)

https://github.com/prometheus-operator/prometheus-operator/commit/bf8476725f96395081ea24f72fb6b6fb8c29df92#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L123

that line seems to keep it from ever actually getting 0.24 which is why #4755 is happening in my testing

**Comment by chrisdotm** [comment]
That said, this commit https://github.com/prometheus-operator/prometheus-operator/commit/2c2ad101f491e41cfb3f6bf83a870aee531fdbe0 seems to have fixed it!

**Comment by PhilipGough** [comment]
Sorry, I failed to notice when looking at the diff that it was a replace directive.

**Comment by PhilipGough** [comment]
@chrisdotm I think you can go ahead and close this since it is superseded by the linked commit

**Pull request closed without merging**
