### PR TITLE
Prepare 0.54.1 release

### PR DESCRIPTION
**Pull request by fpetkovski**
Prepares the 0.54.1 release.

### CODE REVIEW

**Review by PhilipGough — COMMENTED** [review]
@fpetkovski - will we want to bump https://github.com/prometheus-operator/prometheus-operator/blob/main/example/admission-webhook/deployment.yaml also?

**Comment by fpetkovski** [comment]
Looks like that file is not in the 0.54 release, or am I missing something?

**Comment by PhilipGough** [comment]
> Looks like that file is not in the 0.54 release, or am I missing something?

No, you are fully correct :)

**Review by PhilipGough — APPROVED** [review]
lgtm

**Review by paulfantom — APPROVED** [review]
image

**Pull request merged**
