### PR TITLE
pipeline: add docker hub as image push target

### LINKED ISSUE #3234: Docker images mirror on docker hub
**What is missing?**
Prometheus-operator docker image should be made available on docker hub https://hub.docker.com/u/coreos and identified as official image.
This would allow image mirroring on Google Cloud Registry (mirroring only works from docker hub AFAIK)

**Why do we need it?**
Currently, we used quay.io as docker registry.
Since quay.io is currently experiencing an outage (https://status.quay.io/), we're looking to fallback on docker hub (from which we can mirror images on Google Cloud Registry).
We could not find any prometheus-operator docker image there.

**Environment**
GKE

### PR DESCRIPTION
**Pull request by walbertus**
this add mirror image on docker hub to increase image availability

Fixes #3234

### CODE REVIEW

**Comment by walbertus** [comment]
Need to populate `DOCKERHUB_PASSWORD` and `DOCKERHUB_USERNAME` environment variables

**Comment by lilic** [comment]
Update: this PR is waiting for result of https://github.com/coreos/prometheus-operator/issues/3273 so we don't create extra work :)

**Comment by shinebayar-g** [comment]
Any chance this getting merged? Quay is down entire day. It would be nice if there is a mirror repository.

**Comment by paulfantom** [comment]
Since the creation of this PR few things have changed, primarily:
- we migrated to github actions, so travis isn't used anymore
- docker hub introduced pull limits for unauthenticated users

Due to those changes, especially the latter one, I don't think we should add docker hub as a secondary container repository.

**Comment by paulfantom** [comment]
Closing as packages are now built and published to 2 registries and images are available at:
- Quay - [`quay.io`](https://quay.io/organization/prometheus-operator)
- GitHub Container Registry - [`ghcr.io`](https://github.com/orgs/prometheus-operator/packages?repo_name=prometheus-operator)

**Pull request closed without merging**
