### PR TITLE
Generate markdown via crdoc

### PR DESCRIPTION
**Pull request by PhilipGough**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

This is a first pass at fixing #4376 
Uses [crdoc](https://github.com/fybrik/crdoc) to generate from CRD's

I have structured it so that we separate the API versions accordingly.

This is mostly a RFC and therefore I haven't removed any existing files and some files are duplicated to support the splitting of `v1` and `v1alpha1`.

The resulting file for `v1` is quiet large 126k -> 1.4M

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Comment by paulfantom** [comment]
Should we maybe consider creating higher-level `api.md` and putting each CRD doc into a separate doc? It would also be easier to review this way.

side note: I wonder if the alternative tool of `gen-crd-api-reference-docs` creates more markdown-ish files than those htmls from crdoc :thinking:

**Comment by PhilipGough** [comment]
@paulfantom let me try create a similar PR with `gen-crd-api-reference-docs` and we can compare. I personally am not too concerned with the implementation right now, we can flesh that out when we have the correct tool picked.

**Comment by PhilipGough** [comment]
@paulfantom one thing to note, this tool relies on CRD so it is not going to allow us to generate the other docs (compatibility.md etc), from what I can see which is likely a downside, since we would need to still retain po-docgen for that.

**Comment by paulfantom** [comment]
> this tool relies on CRD so it is not going to allow us to generate the other docs (compatibility.md etc),

I am not concerned about this. There are most likely tools to generate other parts of our docs too. Let's start with CRDs and we can iterate on other parts.

**Comment by PhilipGough** [comment]
@paulfantom - interesting report https://github.com/kubeflow/website/issues/1924 of a previous user of `gen-crd-api-reference-docs` migrating away because it is unusable.

**Comment by simonpasquier** [comment]
> I have structured it so that we separate the API versions accordingly.

Works for me. If possible I'd prefer to keep everything in one file per API version. And as such the output of `crdoc` is too large to display in the GitHub UI which is annoying.

> interesting report [kubeflow/website#1924](https://github.com/kubeflow/website/issues/1924) of a previous user of `gen-crd-api-reference-docs` migrating away because it is unusable.

I see that the issue got stale and all issues being mentioned have been resolved?

**Comment by PhilipGough** [comment]
> And as such the output of crdoc is too large to display in the GitHub UI which is annoying.

Yes very large (1.4M) - I'd personally be happy to close this one based on that alone if we intend on being able to display the markdown in GH. If we are more interested in generating html for https://prometheus-operator.dev/ then it might still make sense.

**Comment by paulfantom** [comment]
Too large files may cause issues during PR review process and as such, I am not a fan of merging files with a size of 1.4M.

**Comment by PhilipGough** [comment]
Closing since we are all in agreement the size of the output from this tool is excessive for us.

**Pull request closed without merging**
