### PR TITLE
Add metaconfig configuration to remoteWrite

### PR DESCRIPTION
**Pull request by mikechengwei**
Support #3889.

```release-note:REPLACEME
Add metaconfig configuration to remoteWrite
```

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by lilic** [comment]
Seems like the rebase or merge might have gone wrong, or you need to run make generate again? Thank you!

**Comment by mikechengwei** [comment]
@lilic done.

**Review by lilic — APPROVED** [review]
Thank you!

**Pull request merged**
