### PR TITLE
Drop ksonnet as a dependency in jsonnetfile.json

### PR DESCRIPTION
**Pull request by rajatvig**
Drop the dependency on ksonnet from jsonnetfile.json. 

```release-node:change
Drop ksonnet as a dependency in jsonnetfile.json
```

### CODE REVIEW

**Review by paulfantom — APPROVED** [review]
lgtm on green

**Comment by paulfantom** [comment]
Could you rebase this PR? It may help with e2e tests.

**Comment by rajatvig** [comment]
@paulfantom I rebased but the checks are waiting on approvals

**Comment by rajatvig** [comment]
The tests are passing. Can this be merged?

**Pull request merged**
