### PR TITLE
Admission webhook for AlertmanagerConfig resources

### LINKED ISSUE #3710: Implement admission webhook for AlertmanagerConfig resources
**What is missing?**

Similar to what we have for Prometheus rules, it would be useful to implement an admission webhook endpoint for `AlertmanagerConfig` resources.

**Why do we need it?**

There are validation constraints that can't be modeled in the CRD. To list a few:
* ~~a route needs to reference the name of an existing receiver in the same resource ([link](https://github.com/prometheus-operator/prometheus-operator/blob/fe65bc9ea96270718dd273ea1565d61a7ad3941d/pkg/alertmanager/operator.go#L1091-L1093)).~~ incorrect see #3749 
* Slack actions need to have either an url or a name ([link](https://github.com/prometheus-operator/prometheus-operator/blob/fe65bc9ea96270718dd273ea1565d61a7ad3941d/pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go#L235-L237)).
* sub-routes are only represented as raw JSON data and can only be validated at reconciliation time (#3703).
* url fields need a valid scheme (#4153))

### PR DESCRIPTION
**Pull request by sev3ryn**
Add admission webhook for AlertmanagerConfig resources. Fixes #3710

**Release Note Template (will be copied)**

```release-note:enhancement
Add admission webhook for AlertmanagerConfig resources.
```

### CODE REVIEW

**Comment by brancz** [comment]
Any reason why this was a draft? Nice work!

**Comment by sev3ryn** [comment]
unfortunately, this is quite far from issue solution. I just managed to do some initial refactoring, but got carried away by work stuff. Feel free to take it

**Comment by PhilipGough** [comment]
@simonpasquier this can be closed since #3710 has been dealt with

**Comment by simonpasquier** [comment]
correct, thanks!

**Pull request closed without merging**
