### PR TITLE
*: prepare 0.52.1

### PR DESCRIPTION
**Pull request by fpetkovski**
Prepares the 0.52.1 release

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by fpetkovski** [comment]
The documentation check has been failing for a while and I assumed it's a problem with the CI check.

**Comment by fpetkovski** [comment]
Should we cut a new release in this case?

**Comment by paulfantom** [comment]
No, it is just docs thing, but we should fix it and pay more attention to why checks are failing (especially since one check can fail for multiple reasons).

**Comment by fpetkovski** [comment]
In this case, I suggest splitting the docs check into what is allowed to fail (e.g. checking external links) vs what is not allowed to fail. 

Alternatively, we can remove checking external links if we don't really care whether they fail or not.

**Comment by paulfantom** [comment]
I don't see that helping much. IMHO it would only create a CI configuration at which people would stop looking and start disregarding without improving it. We should be always checking failed CI runs regardless of their allowance to fail. The lack of `Required` label in CI status check doesn't mean we shouldn't check what caused CI job to fail, it only means we can merge the PR with it failing but we still should fix the issue.

**Comment by paulfantom** [comment]
In this particular case, the issue is why `make generate` did not bump the version number in https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/rbac.md?

**Comment by fpetkovski** [comment]
Ok, this looks like a good topic to discuss during our biweekly calls. Maybe we can align on the CI expectations the next time we meet.

**Pull request merged**
