### PR TITLE
Set Read/ReadHeaderTimeouts on http.Server

### PR DESCRIPTION
**Pull request by mrueg**
## Description
via gosec linter - G112: Potential slowloris attack

https://medium.com/a-journey-with-go/go-understand-and-mitigate-slowloris-attack-711c1b1403f6

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Set Read/ReadHeaderTimeouts on http.Server instances
```

### CODE REVIEW

**Review by JoaoBraveCoding — APPROVED** [review]
TIL, that's neat! Thanks for the contribution!

**Comment by PhilipGough** [comment]
I am not convinced about this change if I am honest, particularly the hardcoded nature of the value. Perhaps making them configurable might make sense but my gut feeling tells me that this could/should be mitigated at ingress/proxy layer if required.

**Review by simonpasquier — COMMENTED** [review]
From what I can tell, the timeout for webhook configurations has to be between 1 second and 30 seconds, with a default of 10s for v1 ([ref](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#validatingwebhook-v1-admissionregistration-k8s-io)). I'd be ok with a hardcoded timeout value of 30s so we don't introduce a potentially breaking change.
In addition we should evaluate if there's value in enabling the `gosec` linter. My first impression is that it's a bit noisy but I haven't looked very deep.

**Review by PhilipGough — APPROVED** [review]
lgtm

**Comment by simonpasquier** [comment]
thanks!

**Pull request merged**
