### PR TITLE
Fix inconsistent naming in alertmgr crd

### LINKED ISSUE #3690: Inconsistent naming between base Alertmanager and AlertmanagerConfig CRD receiver keys
The capitalization for the `AlertmanagerConfig` CRD receiver keys differ from how the words are broken up in the base Alertmanager config
https://github.com/prometheus-operator/prometheus-operator/blob/131dad67dd1537387b751f9829ba04dbc3675a00/pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go#L78-L84
vs
```
# Configurations for several notification integrations.
email_configs:
  [ - <email_config>, ... ]
pagerduty_configs:
  [ - <pagerduty_config>, ... ]
pushover_configs:
  [ - <pushover_config>, ... ]
slack_configs:
  [ - <slack_config>, ... ]
opsgenie_configs:
  [ - <opsgenie_config>, ... ]
webhook_configs:
  [ - <webhook_config>, ... ]
victorops_configs:
  [ - <victorops_config>, ... ]
wechat_configs:
  [ - <wechat_config>, ... ]
```
https://prometheus.io/docs/alerting/latest/configuration/#receiver

I can see this going both ways, since the capitalization is consistent with the company branding `WeChat` and `PagerDuty`. I think it makes sense to use the camel casing for separating words (and ignoring the case in branding), in the same way Alertmanager use the snake casing without the branding part. 

I think having this be consistent with Alertmanager makes sense, especially since the word separation is unambiguous.

### PR DESCRIPTION
**Pull request by arghya88**
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>

Fixes #3690

### CODE REVIEW

**Comment by simonpasquier** [comment]
lgtm

**Comment by longtomjr** [comment]
Looks like I have duplicated some of this with #3702. Let me know if you want me to close that PR in favor of this one.

I changed the internal types names and keys as well as the api. I think that is the only major difference.

**Comment by arghya88** [comment]
@lilic @simonpasquier Let me know if anything else is needed or can be merged.

**Comment by simonpasquier** [comment]
thanks!

**Pull request merged**
