### PR TITLE
Refactor ScrapeConfigSpec

### LINKED ISSUE #6815: Update OAuth2 field description in ScrapeConfig CRD
(nit) to be consistent with the other auth fields like `Authorization`.
```suggestion
	// OAuth2 configuration to use on every scrape request.
```

_Originally posted by @simonpasquier in https://github.com/prometheus-operator/prometheus-operator/pull/6814#discussion_r1706665812_

Also unit tests would be nice to add.

### PR DESCRIPTION
**Pull request by mviswanathsai**
## Description

Add testcases and new API validations.

Closes #6815 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Comment by mviswanathsai** [comment]
Haven't created a test yet. Will create the test once we are sure about how we want to split the sub-tests.

**Comment by mviswanathsai** [comment]
I haven't pushed the commit yet, but I am seeing behavior that I cannot explain. 
For example, the `MinLength` validation in the e2e tests is working as expected for most fields. But some fields like `LinodeSDConfigs` or `StaticConfigs` don't work, while very similar fields like `KubernetesSDConfigs` works as expected. This is only limited to the e2e tests though. 
Trying to supply an empty list of `LinodeSDConfigs` or `StaticConfigs` is rejected as we would expect.

**Comment by simonpasquier** [comment]
It would help to print out the err value: it might be that we have an error but not the expected type?

**Comment by mviswanathsai** [comment]
```
=== NAME  TestAllNS/y/ScrapeConfigCRDValidations/ScrapeConfig/EC2SDConfigs:_Empty_List
    scrapeconfig_test.go:534: The error is: <nil>
    scrapeconfig_test.go:535: 
                Error Trace:    /home/mviswanathsai/operator/test/e2e/scrapeconfig_test.go:535
                Error:          Should be true
                Test:           TestAllNS/y/ScrapeConfigCRDValidations/ScrapeConfig/EC2SDConfigs:_Empty_List

=== NAME  TestAllNS/y/ScrapeConfigCRDValidations/ScrapeConfig/DigitalOceanSDConfigs:_Empty_List
    scrapeconfig_test.go:534: The error is: <nil>
    scrapeconfig_test.go:535: 
                Error Trace:    /home/mviswanathsai/operator/test/e2e/scrapeconfig_test.go:535
                Error:          Should be true
                Test:           TestAllNS/y/ScrapeConfigCRDValidations/ScrapeConfig/DigitalOceanSDConfigs:_Empty_List

=== NAME  TestAllNS/y/ScrapeConfigCRDValidations/ScrapeConfig/LinodeSDConfigs:_Empty_List
    scrapeconfig_test.go:534: The error is: <nil>
    scrapeconfig_test.go:535: 
                Error Trace:    /home/mviswanathsai/operator/test/e2e/scrapeconfig_test.go:535
                Error:          Should be true
                Test:           TestAllNS/y/ScrapeConfigCRDValidations/ScrapeConfig/LinodeSDConfigs:_Empty_List

=== NAME  TestAllNS/y/ScrapeConfigCRDValidations/ScrapeConfig/LightSailSDConfigs:_Empty_List
    scrapeconfig_test.go:534: The error is: <nil>
    scrapeconfig_test.go:535: 
                Error Trace:    /home/mviswanathsai/operator/test/e2e/scrapeconfig_test.go:535
                Error:          Should be true
                Test:           TestAllNS/y/ScrapeConfigCRDValidations/ScrapeConfig/LightSailSDConfigs:_Empty_List

=== NAME  TestAllNS/y/ScrapeConfigCRDValidations/ScrapeConfig/StaticConfig:_Empty_List
    scrapeconfig_test.go:534: The error is: <nil>
    scrapeconfig_test.go:535: 
                Error Trace:    /home/mviswanathsai/operator/test/e2e/scrapeconfig_test.go:535
                Error:          Should be true
                Test:           TestAllNS/y/ScrapeConfigCRDValidations/ScrapeConfig/StaticConfig:_Empty_List
```
Other fields with identical validations work as expected in the e2e test.
The only commonality that I can find between the SDs that fail is that **none of them have even a single required field**. I don't think this should affect anything though? Since it works as expected in my local deployment.

**Comment by simonpasquier** [comment]
> The only commonality that I can find between the SDs that fail is that **none of them have even a single required field**. I don't think this should affect anything though? Since it works as expected in my local deployment.

Yeah I think that it's the crux. When the k8s client serializes the payload, it will omit the "empty" field because of the `omitempty` tag. I'm not sure what we can do about it TBH. Maybe we can put this PR on hold (at least the MinItems validation) otherwise it would create inconsistency and confusion.

**Comment by mviswanathsai** [comment]
The problem being, we are experiencing somewhat similar things with StaticConfig, and Consul as well. We can see there that the server does not seem to throw any errors for those objects. Do you reckon that might also be for a similar reason?

**Comment by simonpasquier** [comment]
Probably but I don't have more time to spend on it unfortunately :-/

**Pull request merged**
