### PR TITLE
pkg/alertmanager: sanitize configuration for v0.25.0

### PR DESCRIPTION
**Pull request by simonpasquier**
## Description

Alertmanager v0.25.0 introduces new notifiers (Discord, Webex) + configuration fields that the operator needs to sanitize.
    
Global configuration:
    * `smtp_auth_password_file`
    * `victorops_api_key_file`
    
HTTP client configuration:
    * `proxy_url` for OAuth2
    * `min_version` & `max_version` for TLS
    * `enable_http2`
    
Email configuration:
    * `auth_password_file`
    
PagerDuty configuration:
    * `routing_key_file`
    * `service_key_file`
    * `source`
    
VictorOps configuration:
    * `api_key_file`

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [X] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Supported new fields from Alertmanager v0.25.0
```

### CODE REVIEW

**Review by PhilipGough — APPROVED** [review]
lgtm

**Comment by JoaoBraveCoding** [comment]
This closes https://github.com/prometheus-operator/prometheus-operator/issues/5251, right?

**Review by JoaoBraveCoding — APPROVED** [review]
lgtm

**Comment by simonpasquier** [comment]
> This closes #5251, right?

I've reworded the issue to target the AlertmanagerConfig CRD work. Whenever Alertmnager adds a new option, we have 2 work items on the operator side: 1) support the option in the generated configuration and 2) support the option in the AlertmanagerConfig CRD.

**Review by PhilipGough — APPROVED** [review]

**Pull request merged**
