### PR TITLE
FIX: K8S selector role regression

### LINKED ISSUE #6885: ScrapeConfig: unknown Kubernetes SD role \"Pod\"" when using kubernetesSDConfigs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When deploying scrape config with kubernetesSDConfigs, role is not parsing correctly to prometheus yaml format. Maybe is looking for lowercase but ScrapeConfig kubernetesSDConfigs definition does not support lowercase letters (Pod)

### Prometheus Operator Version

```shell
0.76.0
```

### Kubernetes Version

```yaml
v1.30.2
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### Manifests

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: veeam-k10-pods
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
    app.kubernetes.io/name: scrape-config-k10-pods
spec:
  jobName: k10-pods
  kubernetesSDConfigs:
    - role: Pod
      namespaces:
        ownNamespace: true
      selectors:
        - role: Pod
          label: "component=executor"
  relabelings:
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - sourceLabels: [__meta_kubernetes_pod_container_port_number]
      action: keep
      regex: 8\d{3}
```

### prometheus-operator log output

```shell
ts=2024-08-29T08:24:05.845Z caller=main.go:549 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: unknown Kubernetes SD role \"Pod\""
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mviswanathsai**
## Description
Fixes the Role field bug in the generated K8S Service discovery config.
Closes #6885 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification
The following spec 
```
		{
			name: "kubernetes_sd_config_with_selectors",
			scSpec: monitoringv1alpha1.ScrapeConfigSpec{
				KubernetesSDConfigs: []monitoringv1alpha1.KubernetesSDConfig{
					{
						Role: monitoringv1alpha1.KubernetesRoleNode,
						Selectors: []monitoringv1alpha1.K8SSelectorConfig{
							{
								Role:  "Node",
								Label: ptr.To("component=executor"),
							},
						},
					},
				},
			},
			version: "2.18.0",
			golden:  "ScrapeConfigSpecConfig_K8SSD_with_Selectors.golden",
		},
```
generates the following config:

```
...
scrape_configs:
- job_name: scrapeConfig/default/testscrapeconfig1
  kubernetes_sd_configs:
  - role: node
 ...
```

## Changelog entry
Fix bug with Kubernetes service discovery `Selector.Role` field

```release-note
Fix bug with Kubernetes service discovery `Selector.Role` field
```

### CODE REVIEW

**Comment by mviswanathsai** [comment]
PTAL @simonpasquier @nicolastakashi

**Comment by simonpasquier** [comment]
Can you apply the patch against the release-0.76 branch so we can cut a v0.76.1 release?

**Comment by mviswanathsai** [comment]
My bad, I will re-do this.

**Comment by mviswanathsai** [comment]
Moved to #6896

**Pull request closed without merging**
