### PR TITLE
test/e2e: check user metadata 3 times to reduce test flakiness

### PR DESCRIPTION
**Pull request by paulfantom**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Running flaky test 3 times as a workaround for #4070 issue.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Comment by paulfantom** [comment]
Argh, I forgot to push changes of `t.Errorf` and `t.Fatalf` to `t.Logf`. Now this is done, @simonpasquier please take a look.

**Comment by paulfantom** [comment]
Funny, seems like this doesn't help and test is failing either way due to Secret being incorrect. Maybe our logic of updating that Secret is broken somewhere? :thinking:

**Comment by simonpasquier** [comment]
From https://github.com/prometheus-operator/prometheus-operator/issues/4070#issuecomment-864569764 it seems that adding a wait between the metadata updates and the Prometheus scale up "resolves" the issue but this feels really hacky. My suspicion is that the operator reads a stale secret (e.g. with the updated metadata) but I fail to see how it's possible reading the code...

**Comment by simonpasquier** [comment]
Closed by #4235 :)

**Pull request closed without merging**
