### PR TITLE
pkg/probe: add k8s service support

### PR DESCRIPTION
**Pull request by viperstars**
As we know, we can add probe for ingress now. But k8s service is not supported which is a common requirement like: #3931 and #3923

So I add the k8s service support with some breaking changes in `ProbeTargets`.

```go
// ProbeTargets defines a set of static and dynamically discovered targets for the prober.
// +k8s:openapi-gen=true
type ProbeTargets struct {
	// StaticConfig defines static targets which are considers for probing.
	// More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config.
	StaticConfig *ProbeTargetStaticConfig `json:"staticConfig,omitempty"`
	// DynamicConfig defines the set of dynamically discovered objects which hosts are considered for probing.
	DynamicConfig *ProbeTargetDynamicConfig `json:"dynamicConfig,omitempty"`
}

// ProbeTargetDynamicConfig defines the set of dynamic targets considered for probing.
// +k8s:openapi-gen=true
type ProbeTargetDynamicConfig struct {
	// KubernetesSDConfig is the configuration for Kubernetes service discovery.
	KubernetesSDConfig *KubernetesSDConfig `json:"kubernetesSDConfig,omitempty"`
	// RelabelConfigs to apply to samples before ingestion.
	// More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
	RelabelConfigs []*RelabelConfig `json:"relabelingConfigs,omitempty"`
}

// KubernetesSDConfig is the configuration for Kubernetes service discovery.
// +k8s:openapi-gen=true
type KubernetesSDConfig struct {
	// Role is role of the service in Kubernetes.
	Role string `json:"role,omitempty"`
	// Select objects by labels.
	Selector metav1.LabelSelector `json:"selector,omitempty"`
	// Select objects by namespace.
	NamespaceSelector NamespaceSelector `json:"namespaceSelector,omitempty"`
}
```

The reason why I made these changes is to make the probe easy to configure and extend.

Users can configure the probe like this:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
  name: service-probe
  namespace: monitoring
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc:19115
  targets:
    dynamicConfig:
      kubernetesSDConfig:
        role: service
        selector:
          matchLabels: 
            prometheus.io/tcp_probe: "true"
      relabelingConfigs:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
  name: ingress-probe
  namespace: monitoring
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc:19115
  targets:
    dynamicConfig:
      kubernetesSDConfig:
        role: ingress
        selector:
          matchLabels: 
            prometheus.io/http_probe: "true"
      relabelingConfigs:
        - action: labelmap
          regex: __meta_kubernetes_ingress_label_(.+)
```

If we add endpoint support someday, the old configuration is still compatible and user can add endpoint probe just like they did for ingress and service:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
  name: endpoint-probe
  namespace: monitoring
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc:19115
  targets:
    dynamicConfig:
      kubernetesSDConfig:
        role: endpoint
        selector:
          matchLabels: 
            prometheus.io/tcp_probe: "true"
      relabelingConfigs:
        - action: labelmap
          regex: __meta_kubernetes_endpoint_label_(.+)
```

### CODE REVIEW

**Comment by simonpasquier** [comment]
Rather than changing the `Probe` CRD (which would be a breaking change and require a version bump of the CRD), I think that the idea should be to define a more generic `ScrapeConfig` CRD as expressed in #2787.

**Comment by viperstars** [comment]
> Rather than changing the `Probe` CRD (which would be a breaking change and require a version bump of the CRD), I think that the idea should be to define a more generic `ScrapeConfig` CRD as expressed in #2787.

Yes, `ScrapeConfig` CRD can be used to solve this. But as I know, `ServiceMonitor` /`PodMonitor`/`Probe` are different encapsulations for prometheus scrape config. These CRDs are designed for specified scenarios. As mentioned in the issue, `ScrapeConfig` is more general and designed for scenarios which `ServiceMonitor` /`PodMonitor`/`Probe` can not cover. In my opinion, probing for k8s service is a kind of probe, so it should be covered by `Probe` CRD rather than `ScrapeConfig`.

**Comment by paulfantom** [comment]
> In my opinion, probing for k8s service is a kind of probe, so it should be covered by Probe CRD rather than ScrapeConfig

I agree with this, but I cannot agree with the implementation of `kubernetesSDConfig` as a way to add scraping Service objects. `kubernetesSDConfig` is something that should be a part of generic `ScrapeConfig` and in case of `Probe` we should focus only on objects which make sense for probing for most users (possibly only Ingress and Service) while providing good and easy user experience.

**Comment by viperstars** [comment]
> > In my opinion, probing for k8s service is a kind of probe, so it should be covered by Probe CRD rather than ScrapeConfig
> 
> I agree with this, but I cannot agree with the implementation of `kubernetesSDConfig` as a way to add scraping Service objects. `kubernetesSDConfig` is something that should be a part of generic `ScrapeConfig` and in case of `Probe` we should focus only on objects which make sense for probing for most users (possibly only Ingress and Service) while providing good and easy user experience.

Thanks for the reply. I understand your concern.

How about remove the `KubernetesSDConfig` struct? Just add `Role` in the `ProbeTargetDynamicConfig`.
```go
// ProbeTargets defines a set of static and dynamically discovered targets for the prober.
// +k8s:openapi-gen=true
type ProbeTargets struct {
	// StaticConfig defines static targets which are considers for probing.
	// More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config.
	StaticConfig *ProbeTargetStaticConfig `json:"staticConfig,omitempty"`
	// DynamicConfig defines the set of dynamically discovered objects which hosts are considered for probing.
	DynamicConfig *ProbeTargetDynamicConfig `json:"dynamicConfig,omitempty"`
}

// ProbeTargetDynamicConfig defines the set of dynamic targets considered for probing.
// +k8s:openapi-gen=true
type ProbeTargetDynamicConfig struct {
  // Role is role of the service in Kubernetes.
	Role string `json:"role,omitempty"`
	// Select objects by labels.
	Selector metav1.LabelSelector `json:"selector,omitempty"`
	// Select objects by namespace.
	NamespaceSelector NamespaceSelector `json:"namespaceSelector,omitempty"`
	// RelabelConfigs to apply to samples before ingestion.
	// More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
	RelabelConfigs []*RelabelConfig `json:"relabelingConfigs,omitempty"`
}
```

User can configure `Probe` as follow:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
  name: service-probe
  namespace: monitoring
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc:19115
  targets:
    dynamicConfig:
      role: service
      selector:
        matchLabels: 
          prometheus.io/http_probe: "true"
      relabelingConfigs:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
  name: ingress-probe
  namespace: monitoring
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc:19115
  targets:
     dynamicConfig:
      role: ingress
      selector:
        matchLabels: 
          prometheus.io/http_probe: "true"
      relabelingConfigs:
        - action: labelmap
          regex: __meta_kubernetes_ingress_label_(.+)
```

If we don't expect any breaking changes, we can add `ProbeTargetService` like this:

```go
type ProbeTargets struct {
	// StaticConfig defines static targets which are considers for probing.
	// More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config.
	StaticConfig *ProbeTargetStaticConfig `json:"staticConfig,omitempty"`
	// Ingress defines the set of dynamically discovered ingress objects which hosts are considered for probing.
	Ingress *ProbeTargetIngress `json:"ingress,omitempty"`
        // Service defines the set of dynamically discovered service objects which endpoints are considered for probing.
        Service *ProbeTargetService `json:"ingress,omitempty"`
}

// ProbeTargetService defines the set of Service objects considered for probing.
// +k8s:openapi-gen=true
type ProbeTargetService struct {
	// Select Service objects by labels.
	Selector metav1.LabelSelector `json:"selector,omitempty"`
	// Select Service objects by namespace.
	NamespaceSelector NamespaceSelector `json:"namespaceSelector,omitempty"`
	// RelabelConfigs to apply to samples before ingestion.
	// More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
	RelabelConfigs []*RelabelConfig `json:"relabelingConfigs,omitempty"`
}
```

But I think it is not a good way. If user configure `Ingress` and `Service` at the same time, we must generate two different scrape jobs. This may make user confused.

**Comment by simonpasquier** [comment]
>  If user configure Ingress and Service at the same time, we must generate two different scrape jobs. This may make user confused.

Looking at the code, they would already confused if they configured static and ingress probes at the same time because the operator would only generate configuration for the static probes (see [here](https://github.com/prometheus-operator/prometheus-operator/blob/67a6f56d426ed87940af301cfd0833facd2b3af7/pkg/prometheus/promcfg.go#L728-L777)). I don't recall the exact reason why it's been implemented this way (@lilic?) but it needs to be advertised in the documentation at least.

**Comment by viperstars** [comment]
> > If user configure Ingress and Service at the same time, we must generate two different scrape jobs. This may make user confused.
> 
> Looking at the code, they would already confused if they configured static and ingress probes at the same time because the operator would only generate configuration for the static probes (see [here](https://github.com/prometheus-operator/prometheus-operator/blob/67a6f56d426ed87940af301cfd0833facd2b3af7/pkg/prometheus/promcfg.go#L728-L777)). I don't recall the exact reason why it's been implemented this way (@lilic?) but it needs to be advertised in the documentation at least.

Yes, at first I tried to add service support in the second way. But I found it is hard to do. As you mentioned, if user add `ProbeTargetStaticConfig` and `ProbeTargetIngress` at the same time, we will only generate scrape config for `staticTarget`. If I continue to add the `ProbeTargetService` in `ProbeTargets`. I need decide which target to generate and which to ignore then I need to send message to user that some of the target is ignored. This logic must be mentioned in the doc to prevent user configuring multiple targets at the same time. For this reason, I prefer the first way. We only need to emphasize user not to configure `StaticConfig` and `DynamicConfig` at the same time.

**Pull request closed without merging**
