### PR TITLE
chore: move ProxyConfig type to v1

### PR DESCRIPTION
**Pull request by slashpai**
Related-to #6301

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [x] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
chore: move ProxyConfig type to v1
```

### CODE REVIEW

**Comment by slashpai** [comment]
As a first step I moved the ProxyConfig type to v1 so that we can utilize it in v1.OAuth2 as wel. IIUC we don't need to have a separate type again in v1 for this?

**Review by ArthurSens — APPROVED** [review]
LGTM

**Comment by slashpai** [comment]
Had to rebase to fix merge conflicts, please review again :)

**Comment by slashpai** [comment]
Looks like k8s slack has dns issues?

```
error: 3 errors:
		CONTRIBUTING.md:31: "https://slack.k8s.io/" not accessible; status code 403: Forbidden
		MAINTAINERS.md:16: "https://slack.k8s.io/" not accessible; status code 403: Forbidden
		README.md:5: "http://slack.k8s.io/" not accessible; status code 403: Forbidden
```

**Review by simonpasquier — APPROVED** [review]
lgtm

**Pull request merged**
