### PR TITLE
removal of deprecated config-reloader resource flags for #3883

### PR DESCRIPTION
**Pull request by JJJJJones**
#3883 

Which version should this be merged into, 0.48.0 or 0.49.0? #3826 didn't get merged in time for the 0.46.0 release and was intended to be part of that. I'll commit the `make generate` results for that version.

**Release Note Template (will be copied)**

```release-note:change
Remove deprecated flags `--config-reloader-memory` and `--config-reloader-cpu` in favor of `--config-reloader-memory-limit`, `--config-reloader-memory-request`, `--config-reloader-cpu-limit`, and `--config-reloader-cpu-request`
```

### CODE REVIEW

**Comment by simonpasquier** [comment]
It should target 0.49.0 since the new flags would only be available with 0.47.0.

**Comment by JJJJJones** [comment]
> It should target 0.49.0 since the new flags would only be available with 0.47.0.

Awesome, i'll build off of 0.49.0 and commit.

**Comment by JJJJJones** [comment]
Updated the PR to remove the code for rc* now that its vestigial.

`make-generate` and `make test-unit` have been run with no changes to anything.

**Comment by JJJJJones** [comment]
For some reason successive runs of `make generate` and `make format` behave differently to `make format generate`. Committing results of that.

**Comment by simonpasquier** [comment]
lgtm

**Pull request merged**
