### PR TITLE
Backport PRs #3126,#3179,#3182,#3233

### PR DESCRIPTION
**Pull request by benjaminhuo**
Backport PRs #3126,#3179,#3182,#3233 and their dependencies

### CODE REVIEW

**Comment by metalmatze** [comment]
Who wants to take a look at this? This is going into v0.38. :)

**Comment by benjaminhuo** [comment]
I can do the release stuff, just let me know the steps :)

**Comment by paulfantom** [comment]
We just hit an issue which is possibly caused in some part by https://github.com/coreos/prometheus-operator/pull/3182 so I would prefer to gather more insight before merging this PR.

/cc @simonpasquier

**Comment by simonpasquier** [comment]
Do we still need this to be backported to 0.38 knowing that all those patches are available since v0.40.0 (and the latest release is v0.41.1)?

**Comment by benjaminhuo** [comment]
@simonpasquier We have use cases to support k8s < 1.16, that's why I created this PR. 
Prometheus operator doesn't support K8s 1.15 and below anymore since 0.39：
`[CHANGE] Switch to apiextensions.k8s.io/v1 CRD and require kubernetes v1.16 or newer (#3175, #3187)`

**Comment by simonpasquier** [comment]
Merging since we had @brancz approval already.

**Pull request merged**
