### PR TITLE
Ignore invalid CRDs and pick up valid CRDs without failing and add validation for relabeling and metricRelabeling fields for pod/svc monitors

### PR DESCRIPTION
**Pull request by rashmichandrashekar**
## Description

When a podmonitor/svcmonitor CRD has an erraneous field for regex in the relabeling/metric relabeling fields, the crd creation succeeds since it can be a valid string but not a valid regex( ex- .*( ). This causes any subsequent valid CRDs being created from getting picked up. Also, the current generatePodMonitorConfig/generateServiceMonitorConfig doesnt do any validation for relabeling/metricRelabeling. Can leverage the **validateRelabelConfig** method here - https://github.com/prometheus-operator/prometheus-operator/blob/dfc150aa362f0260060979d0b53a524efb974168/pkg/prometheus/resource_selector.go#L236

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [X] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [X] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry
```release-note
Add validation for relabeling/metricsRelabeling for pod/service monitor and continue picking up valid CRDs and ignore invalid CRDs
```

### CODE REVIEW

**Comment by slashpai** [comment]
Relabel configs are validated while selecting servicemonitors/podmonitors eg: https://github.com/prometheus-operator/prometheus-operator/blob/dfc150aa362f0260060979d0b53a524efb974168/pkg/prometheus/resource_selector.go#L155-L163. 

This is not checked while generating since we will be rejecting once that are failing the validation instead of failing the reconciliation due to one/few wrong servicemonitors.

**Comment by simonpasquier** [comment]
What @slashpai says: at this stage, invalid configs have already been rejected.

**Comment by rashmichandrashekar** [comment]
@slashpai @simonpasquier - Thanks for taking a look. Is it okay to expose this method [validateRelabelConfig](https://github.com/prometheus-operator/prometheus-operator/blob/5f1a151a48d3ec71230c09e0ab4575b0a26560a9/pkg/prometheus/resource_selector.go#L237) so that others consuming this package, who dont take the same route as through the resource selector can reuse the validation and can have it consistent with the prom-operator?
I can make a PR for that.

**Comment by simonpasquier** [comment]
Can you create a new issue in this repository to discuss the general approach with all @prometheus-operator/prometheus-operator-reviewers?
While you have one specific request now, I bet that the topic will come up again in the future and it's be preferred that we get to a general agreement across all maintainers regarding code reuse by other projects.

**Comment by rashmichandrashekar** [comment]
> Can you create a new issue in this repository to discuss the general approach with all @prometheus-operator/prometheus-operator-reviewers? While you have one specific request now, I bet that the topic will come up again in the future and it's be preferred that we get to a general agreement across all maintainers regarding code reuse by other projects.

@simonpasquier - Created this issue - https://github.com/prometheus-operator/prometheus-operator/issues/6076. Hope this helps.

**Pull request closed without merging**
