### PR TITLE
Add --use-endpoint-slices flag to toggle EndpointSlice vs Endpoints service discovery

### PR DESCRIPTION
**Pull request by thaniri**
## Description

This is a solution to https://github.com/prometheus-operator/prometheus-operator/issues/3862

This introduces a command line flag to toggle service discovery via [EndpointSlices](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/). This will necessarily require a patch to [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) that looks something like this:

<details>
  <summary>kube-prometheus-stack patch</summary>
  
  Shows what changes were required to the kube-prometheus-stack helm chart to configure this command line flag.
  
  ```
  diff --git a/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml b/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
  index 342f3882..3ceaf0fe 100644
  --- a/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
  +++ b/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
  @@ -132,6 +132,9 @@ spec:
               {{- if .Values.prometheusOperator.secretFieldSelector }}
               - --secret-field-selector={{ tpl (.Values.prometheusOperator.secretFieldSelector) $ }}
               {{- end }}
  +            {{- if .Values.prometheusOperator.useEndpointSlices }}
  +            - --use-endpoint-slices=true
  +            {{- end}}
               {{- if .Values.prometheusOperator.clusterDomain }}
               - --cluster-domain={{ .Values.prometheusOperator.clusterDomain }}
               {{- end }}
  diff --git a/charts/kube-prometheus-stack/values.yaml b/charts/kube-prometheus-stack/values.yaml
  index 5dd92fbd..3065598c 100644
  --- a/charts/kube-prometheus-stack/values.yaml
  +++ b/charts/kube-prometheus-stack/values.yaml
  @@ -2188,6 +2188,7 @@ prometheus-node-exporter:
   ##
   prometheusOperator:
     enabled: true
  +  useEndpointSlices: false
 
     ## Use '{{ template "kube-prometheus-stack.fullname" . }}-operator' by default
     fullnameOverride: ""
  ```
</details>

I did not carry on from https://github.com/prometheus-operator/prometheus-operator/pull/6518 as I was unable to figure out how to set the `commonPrometheusFields` configuration of `serviceDiscoveryRole` in the `kube-prometheus-stack` helm chart and then plumb that down to the `generateServiceMonitorConfig` function found in this operator. This solution importantly *unblocks users of this operator* who are using clusters > 1,000 nodes as it provides a configuration for them to use `EndpointSlices` for service discovery. If anyone is able to walk me through how to do said plumbing, I'd be more than happy to update my branch found on my [fork](https://github.com/thaniri/prometheus-operator/tree/issue3862thaniri). It's just not clear to me from [documentation](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.CommonPrometheusFields) how these configs are actually set. 

## Type of change

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

This can be tested by deploying the `kube-prometheus-stack` helm chart with the above patch. When `useEndpointSlices` is set to `true` then the generated scrape configs will have a `kubernetes_sd_role` of `endpointslices` otherwise if `useEndpointSlices` is unset or set to `false` then the generated scrape configs will have a `kubernetes_sd_role` of `endpoints`.

## Changelog entry

```release-note
[ENHANCEMENT] Add --use-endpoint-slices flag to toggle use of EndpointSlices for service discovery.
```

### CODE REVIEW

**Comment by simonpasquier** [comment]
Thanks for the pull requests. The solution we agreed upon in #6518 was to expose the option in the Prometheus & PrometheusAgent CRDs which offer the most flexibility. While I understand that the CLI flag provides an immediate solution to your problem, I'm afraid that it will create confusion in the long run because we'll have 2 ways to accomplish the same thing eventually.

**Comment by thaniri** [comment]
@simonpasquier I have a branch that does the same plumbing as this one but using the modified CRDs based off of https://github.com/prometheus-operator/prometheus-operator/pull/6518

If anyone could show me how I can use the `kube-prometheus-stack` to `helm install` the chart and provide the necessary `commonPrometheusFields.serviceDiscoveryRole` values somewhere then I could verify that the branch works and close this PR. That is the part I was trying to figure out, the code itself was the easier part.

If no-one can help me, then in the short run this PR can unblock users of the `prometheus-operator`.

**Comment by thaniri** [comment]
Closing, will open a PR that exposes the option via CRD.

**Comment by ArthurSens** [comment]
> @simonpasquier I have a branch that does the same plumbing as this one but using the modified CRDs based off of #6518
> 
> If anyone could show me how I can use the `kube-prometheus-stack` to `helm install` the chart and provide the necessary `commonPrometheusFields.serviceDiscoveryRole` values somewhere then I could verify that the branch works and close this PR. That is the part I was trying to figure out, the code itself was the easier part.
> 
> If no-one can help me, then in the short run this PR can unblock users of the `prometheus-operator`.

Usually, we can test this kind of thing with unit or e2e tests (see [testing.md](https://github.com/prometheus-operator/prometheus-operator/blob/main/TESTING.md))

You probably want to add a test in `pkg/prometheus/promcfg_test.go` that verifies if the generated configuration changed as you expect when you set this new field in the CRD

**Pull request closed without merging**
