### PR TITLE
docs(storage): add example for getting prometheus res name

### PR DESCRIPTION
**Pull request by apgapg**
## Description

This PR aims at adding an example command to get the actual name of the Prometheus resource. Begineers may find it difficult to understand.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
docs(storage): add example for getting prometheus res name
```

### CODE REVIEW

**Review by JoaoBraveCoding — COMMENTED** [review]
I appreciate the effort but I'm not entirely sure this addition makes sense in this document. This walkthrough covers a topic which is mainly looked up by a more experienced user base.
Nevertheless, if you feel like this is not clear in our documentation we could maybe introduce something similar in the more beginner-friendly documents we have.

**Comment by apgapg** [comment]
Thank you for replying.

`example` in docs doesnt seems to convey which resource or CRD we are referring too.
Thats why I added the command to let user know which CRD we are talking about

**Comment by simonpasquier** [comment]
I'd recommend to rewrite the commands with environment variable substitution and fail if the variable isn't set. Something like:

```
export PROMETHEUS_NAME=example # Replace with the name of the Prometheus resource that needs to be patched
kubectl patch "prometheus/${PROMETHEUS_NAME:?}" --patch ...
````

**Comment by apgapg** [comment]
@simonpasquier `kubectl patch "prometheus/${PROMETHEUS_NAME:?}" --patch ...` this syntax seems much better as whenever a new comer runs this command, this would auto fail, making him to find out the actual name.

**Pull request closed without merging**
