### PR TITLE
bump prometheus version to v2.27

### LINKED ISSUE #4030: Prometheus operator validating webhook doesn't accept last_over_time function in rule expression
**What happened?**
Trying to apply
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox-exporter.records
spec:
  groups:
  - name: probe
    rules:
    - record: target_pod:probe_success:last_over_24h
      expr: last_over_time(probe_success[24h])
```
ends with an error
```
The  "prometheusrules" is invalid: : 1:45: group "probe", rule 1, "target_pod:probe_success:last_over_24h": could not parse expression: 1:1: parse error: unknown function with name "last_over_time"
```
Promtool says the rule is fine
```
❯ promtool check rules rules.yaml
Checking rules.yaml
  SUCCESS: 1 rules found
```

**How to reproduce it (as minimally and precisely as possible)**:
Run `kubectl apply -f manifest.yaml` with above manifest and expect an error.

**Environment**

* Prometheus Operator version: v0.47.0
* Prometheus version: v2.26.0

### PR DESCRIPTION
**Pull request by mikechengwei**
Closes #4030 .
go get github.com/prometheus/prometheus@db7f0bcec27bd8aeebad6b08ac849516efa9ae02
bump prometheus version to v2.26
```release-note:REPLACEME
Bump prometheus pkg version to v2.27.
```

### CODE REVIEW

**Comment by simonpasquier** [comment]
could you also update [here](https://github.com/prometheus-operator/prometheus-operator/blob/bf4f6bf2a4d46593080856bdfa69a44beab3607b/pkg/operator/defaults.go#L73) and add v2.26.1, v2.27.0 and v2.27.1?

**Comment by mikechengwei** [comment]
@simonpasquier Please have a look again.

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by simonpasquier** [comment]
Thanks!

**Pull request merged**
