### PR TITLE
Update Prometheus and Thanos versions

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Review by brancz — APPROVED** [review]

**Comment by simonpasquier** [comment]
For some unexpected reason, this breaks the remote write e2e tests. I'll need to dig further...

**Review by s-urbaniak — APPROVED** [review]
lgtm, thank you!

**Comment by s-urbaniak** [comment]
@simonpasquier out of curiosity: what was the rationale for removing openssl in favor of Go, not that I suggest to go back but I am literally curious :-)

**Comment by simonpasquier** [comment]
> what was the rationale for removing openssl in favor of Go, not that I suggest to go back but I am literally curious :-)

1) I couldn't find the exact combination of `openssl` CLI flags that would generate the certificates with all required fields.
2) it should be agnostic of the platform (e.g. Linux vs Mac).

We could even take it one step further: remove these certificates from the repository and generate one-time certificates before running the tests.

**Pull request merged**
