### PR TITLE
chore: add +optional markers

### PR DESCRIPTION
**Pull request by simonpasquier**
## Description

To follow https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Review by ArthurSens — APPROVED** [review]
Looking at the link you provided I see
```
They are a pointer type in the Go definition (e.g. AwesomeFlag *SomeFlag) or have a built-in nil value (e.g. maps and slices).
```

Do you know if `Duration` provide a built-in nil value?

**Comment by JoaoBraveCoding** [comment]
>  Do you know if Duration provide a built-in nil value?

IIUC, no since it's a string, so it should be a pointer. But I'm also not sure we can change it 🤔 

Seems like the docs part of the CI is not happy

**Comment by ArthurSens** [comment]
@simonpasquier do you want to merge this one as it is and take a look at adding pointers to strings later? Or should we wait for the pointers?

I'm fine with both, just need to open an issue for the former if that's how we go forward

**Comment by simonpasquier** [comment]
I'll update the PR to have *Duration fields.

**Comment by simonpasquier** [comment]
The PR has been updated to use pointers instead of values.

**Pull request merged**
