### PR TITLE
*: fix generator by adding dependencies on config.jsonnet

### PR DESCRIPTION
**Pull request by paulfantom**
Follow-up to #3781. Add dependencies on a new target.

Tested on Linux by executing:
```
echo 0.99.0 > VERSION
make generate
```
The above should change version number in all files it is used.

/cc @lilic can you test this on MacOS?

**Release Note Template (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by paulfantom** [comment]
Moving to WIP as this still doesn't work on MacOS

**Comment by paulfantom** [comment]
I think this should now work. @lilic can you verify?

**Review by lilic — APPROVED** [review]
Yay forgot to report, this works for me on mac with native `sed`. Thank you!!

We can remove WIP and merge now, right?

**Comment by paulfantom** [comment]
After @simonpasquier suggestion I found a way to get rid of `sed` and just do this in jsonnet. It should be much better now ;)

**Review by lilic — APPROVED** [review]
lgtm

Works for me on Mac as well 🎉

**Pull request merged**
