### PR TITLE
pkg/prometheus/operator.go: Update logger message

### PR DESCRIPTION
**Pull request by slashpai**
This change is to have statefulset shard info in logger msg

Signed-off-by: Jayapriya Pai <slashpai9@gmail.com>

Updated as per https://github.com/prometheus-operator/prometheus-operator/pull/4100#discussion_r650013812

**Release Note Template (will be copied)**

```release-note:REPLACEME
Have statefulset shard info in logger msg
```

### CODE REVIEW

**Review by paulfantom — APPROVED** [review]
lgtm

**Comment by simonpasquier** [comment]
I think we can take it one step further and make sure that all logs in the `sync()` functions report which "key" is being processed (like here [](https://github.com/prometheus-operator/prometheus-operator/blob/2b93704fc1d1d5dbc4e7aa98c2a1425a48bbca42/pkg/alertmanager/operator.go#L747)).

**Comment by slashpai** [comment]
Updated in alertmanager and thanos-ruler

**Comment by slashpai** [comment]
@simonpasquier Can you review if updated changes are fine?

**Review by simonpasquier — COMMENTED** [review]
you can do the same change in the `sync()` function of `pkg/prometheus/operator.go` (starting at L1226).

**Comment by slashpai** [comment]
@simonpasquier Updated

**Pull request merged**
