### PR TITLE
fix: convert consul scheme to lowercase while setting prometheus config

### PR DESCRIPTION
**Pull request by slashpai**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Noticed while playing around ConsulSD config `Scheme` should be converted to lowercase to fix error ` unsupported protocol scheme \"HTTPS\""` from Prometheus

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
fix: convert consul scheme to lowercase while setting prometheus config
```

### CODE REVIEW

**Comment by slashpai** [comment]
> There are a couple more places where we can do the same I believe.

The one on ScrapeConfigSpec is already taken care https://github.com/prometheus-operator/prometheus-operator/blob/b6610bb4e12c73d85dff5d238870fb85f9390b00/pkg/prometheus/promcfg.go#L2284-L2286

I don't see scheme used in other ScrapeConfigs

**Comment by simonpasquier** [comment]
https://github.com/prometheus-operator/prometheus-operator/blob/b6610bb4e12c73d85dff5d238870fb85f9390b00/pkg/prometheus/promcfg.go#L716-L718
https://github.com/prometheus-operator/prometheus-operator/blob/b6610bb4e12c73d85dff5d238870fb85f9390b00/pkg/prometheus/promcfg.go#L927-L929
https://github.com/prometheus-operator/prometheus-operator/blob/b6610bb4e12c73d85dff5d238870fb85f9390b00/pkg/prometheus/promcfg.go#L1180-L1182
https://github.com/prometheus-operator/prometheus-operator/blob/b6610bb4e12c73d85dff5d238870fb85f9390b00/pkg/prometheus/promcfg.go#L1582-L1585

**Comment by slashpai** [comment]
I was looking in ScrapeConfig CRD :)

For others some doesn't have validation api level and some are using http/https. 
Do we want to update api checks as well?

**Review by simonpasquier — APPROVED** [review]
My bad!

**Pull request merged**
