### PR TITLE
kube-prometheus: fix typo in grafana

### PR DESCRIPTION
**Pull request by birdayz**

### CODE REVIEW

**Comment by brancz** [comment]
This dashboard is defined in the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) project, and just used as a dependency in this repository. Could you open a PR there to fix this? Thanks!

**Comment by birdayz** [comment]
alright. opened https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/174

**Comment by brancz** [comment]
merged now in this repo just run `make clean generate-in-docker` in the root of the repo and commit the changes :slightly_smiling_face:

**Comment by birdayz** [comment]
when i run it, it just "reverts" back to the old state. how do i tell the generator to use the newer version of kubernetes-mixin?

**Comment by brancz** [comment]
ah sorry, in the `contrib/kube-prometheus` directory you first need to run `jb update`

**Comment by metalmatze** [comment]
This needs to be rebased, then lgtm.

**Comment by birdayz** [comment]
done

**Comment by birdayz** [comment]
i'm a bit surprised; if i'm not wrong the changes are still not in  after running these two commands..

**Comment by brancz** [comment]
huh, actually I'm just as surprised

**Comment by metalmatze** [comment]
kube-prometheus just moved to https://github.com/coreos/kube-prometheus. 
See [contrib/kube-prometheus/README.md](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/README.md) for details.

Thank you for your contribution and sorry for the inconvenience!

**Comment by paulfantom** [comment]
Closing as kube-prometheus moved.

**Pull request closed without merging**
