### PR TITLE
Enable revive

### PR DESCRIPTION
**Pull request by ArthurSens**
## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [X] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
I remember #3654 which was dismissed because of potential noisiness. I haven't looked into details how misspell works though.

**Comment by ArthurSens** [comment]
> I remember #3654 which was dismissed because of potential noisiness. I haven't looked into details how misspell works though.

I think the misspell PR is https://github.com/prometheus-operator/prometheus-operator/pull/6209, not this one :)

And it caught only 2 misspells, which were valid ones

**Comment by ArthurSens** [comment]
So... is enabling revive in the tests framework ok? :)

**Review by simonpasquier — APPROVED** [review]
LGTM

**Pull request merged**
