### PR TITLE
Adds labels and annotations to PrometheusRule CR

### PR DESCRIPTION
**Pull request by JoaoBraveCoding**
Signed-off-by: Joao Marcal <jmarcal@redhat.com>

## Description

Issue: https://github.com/prometheus-operator/prometheus-operator/issues/5050

Problem: described in the issue. Furthermore, it also fixes the function mergeKubectlAnnotations where previously it was working only because the to map was being modified inside the function mergeMapsByPrefix.

Solution: Additions of labels and annotations to PrometheusRule CR that are then merged into each rule. If a rule already defines a key it will not be overwritten. Regarding mergeKubectlAnnotations function now correctly sets the result of mergingMaps to "to" instead of "from". MergeMapsByPrefix now creates a new map so the original remain intact.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Adds global labels and annotations to PrometheusRule CR that will be added to all rules in groups
```

### CODE REVIEW

**Comment by simonpasquier** [comment]
I think that your change isn't exactly what was requested. The ask is to define labels/annotations at the PrometheusRule level that are injected in every alerting/recording rule of every rule group.

Given

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-example-rules
spec:
  labels:
    label1: label_val1
  annotations:
    annotation1: annotation_val1
  groups:
  - name: example.rules
    rules:
    - alert: ExampleAlert
      expr: vector(1)
      labels:
        label1: overriden
    - record: zero
      expr: vector(0)
```

The resulting Prometheus config file would look like:

```yaml
groups:
- name: example.rules
  rules:
  - alert: ExampleAlert
    expr: vector(1)
    labels:
      label1: overriden # existing label value is retained.
    annotations:
      annotation1: annotation_val1
  - record: zero
      expr: vector(0)
    labels:
      label1: label_val1
    # no annotation because not supported for recording rules.
```

ping @gberche-orange to keep me honest.

**Comment by gberche-orange** [comment]
thanks @JoaoBraveCoding and @simonpasquier. The wording by both of you seem correct to me, and I have a hard time reading the tests at https://github.com/prometheus-operator/prometheus-operator/pull/5100/files#diff-dee0fd2fb1a5d5093af4ed100731310b27b020ffda23cef4e1c97440fed04e23 to find out how tests differs from the above wording.

**Comment by simonpasquier** [comment]
We clarified off-line with @JoaoBraveCoding: I was confused in my initial review and the PR is doing the right thing.
Quick feedback for now:
* Annotations shouldn't be copied to recording rules.
* The fields descriptions should be updated to make it clear that it applies to rules, not Kubernetes objects.

**Comment by JoaoBraveCoding** [comment]
agreed 👍

**Review by paulfantom — COMMENTED** [review]
Wouldn't https://github.com/prometheus/prometheus/pull/11474 essentially solve the root issue (ability to add metadata to all alerts in a group/CR)? If that PR gets implemented I don't see why we would need to add a 3rd level of defining labels/annotations for alerts.

And if we still need this, I would propose to do a cascading propagation through the levels. Basically if someone sets `spec.labels`, operator would only set `spec.groups[].labels` instead of going through all alerts.

**Comment by simonpasquier** [comment]
@paulfantom agreed that we need to see where https://github.com/prometheus/prometheus/pull/11474 is going.

**Pull request closed without merging**
