### PR TITLE
docs: fix linting user-guide with updated docker image

### PR DESCRIPTION
**Pull request by barakplasma**
# Summary
Fixes a bug in the example script as mentioned in #3667 

# The Bug
**Expected:**
Example script lints a sub-directory full of Prometheus Operator CRD files with ether local po-lint or Dockerized version
**Actual:**
Because the previous Docker image was deprecated/removed, the script no longer works; leaving no working po-lint example using the po-tooling docker image.

# The Fix
I updated the script to use the new po-tooling docker image.

## Alternative fixes
I would be happy to simplify the docs significantly by instead providing two short and separate examples for users without the need for a new user to parse this shell script to understand how to run the docker / local commands.

### CODE REVIEW

**Comment by simonpasquier** [comment]
@barakplasma do you really mean to close this PR?

**Comment by barakplasma** [comment]
> @barakplasma do you really mean to close this PR?

I am having trouble with the GitHub mobile app, disregard me closing this

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by simonpasquier** [comment]
Thanks!

**Comment by barakplasma** [comment]
Thank you @simonpasquier !

**Pull request merged**
