### PR TITLE
Update metalmatze's company

### PR DESCRIPTION
**Pull request by metalmatze**
:ice_cube:

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]
:tada:

**Comment by metalmatze** [comment]
Hopefully this change doesn't break e2e tests :sweat_smile:

**Comment by lilic** [comment]
🆒  change!

**Comment by paulfantom** [comment]
CI doesn't like this change, @metalmatze you need to revert your company change :stuck_out_tongue:

**Pull request merged**
