### PR TITLE
Expose Liveness probe params

### PR DESCRIPTION
**Pull request by kousik93**
Hi there. This PR is for exposing the liveness, readiness probe params, `webReadTimeout` and `webMaxConnections`.

Our Prometheus was taking a good amount of time to load all the storage blocks and start answering the probes. As a result, it kept getting killed. Exposing this would really help fine tune the installation.

I've tried to keep the defaults same as before so people who don't use them shouldn't see a difference.

### CODE REVIEW

**Comment by brancz** [comment]
I would prefer not to expose these. Instead I think the liveness probe is actually more harmful than useful, I think we should just remove it. The readiness probe I’m willing to increase the total tries up to 1h instead of what we have today.

**Comment by johngmyers** [comment]
The liveness probe should be changed to return success while it is loading the storage blocks. I don't think it should be removed completely; there should be something to restart the pod if it locks up completely.

**Comment by kousik93** [comment]
I have modified this PR to just have the liveness parameters exposed so as to focus on just that.
I will make a separate PR for exposing readiness.

**Comment by kousik93** [comment]
We are using prometheus version 2.12. We have on average around 1.5 mil to 2mil head time series per cluster. There are scenarios either after an cardinality explosion or even after a manual kill of the prometheus Pod, where prometheus takes a long time to load its blocks and startup. 

During this time, liveness probe fails. As a result, Kubernetes kills the container in the process of starting up. This loop keeps happening. I believe, the default liveness settings offered are too short for our use case. Especially after a cardinality explosion, we increase the memory and start prometheus up again. This issue is specially with liveness probe and only during startup times.

Ideally, we would like prometheus to have a fix for liveness during startup times. If not, in the meantime, atleast control over initial delay seconds will help. Would prefer to keep failure threshold low as to fail fast is issues arise during normal operation.

**Comment by brancz** [comment]
> Ideally, we would like prometheus to have a fix for liveness during startup times.

I agree, this is what we should focus on I think.

> If not, in the meantime, atleast control over initial delay seconds will help. Would prefer to keep failure threshold low as to fail fast if issues arise during normal operation.

Could we as a compromise change the default we have now, and once Prometheus' behavior is fixed we change this value depending on the version deployed?

**Comment by paulfantom** [comment]
> If not, in the meantime, atleast control over initial delay seconds will help

This is exactly what startupProbe is for as per [kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes). We have an issue about it in https://github.com/coreos/prometheus-operator/issues/3211

**Comment by kousik93** [comment]
> Could we as a compromise change the default we have now, and once Prometheus' behavior is fixed ([prometheus/prometheus#3650]

I agree main focus would be to fix Prometheus directly. Which default variable would you like me to change here? The inital delay for our setup would atleast need 7 minutes. For others it might not take so long. Even a higher hardcoded value might not work for everyone. Also, integration tests might take considerably longer (if its an issue at all)


> This is exactly what startupProbe is for as per [kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes). 

I do not mind changing this PR to expose startupProbe instead, if i can get a consensus. I feel this fits the criteria nicely.

Maybe the upstream prometheus fix can also consider this option? Have 3 probes - startup, liveness, readiness? This might decrease the behavior complexity of the individual probes.

**Comment by paulfantom** [comment]
> The inital delay for our setup would at least need 7 minutes.

With `startupProbe` we can have even longer periods while not impacting `livenessProbe`.

> Maybe the upstream prometheus fix can also consider this option? Have 3 probes - startup, liveness, readiness?

If https://github.com/prometheus/prometheus/issues/3650 gets fixed, then `startup` probe endpoint is the same one as `liveness` probe. The only difference is from k8s perspective, not prometheus, so I don't see any additional value for implementing it in prometheus itself.

**Comment by inoam** [comment]
@brancz I would also like configuring liveness probe.
We have noticed that upon node reboot testing, where many pod migrate and restarted etc, prometheus get timeouts and restarted.
The point is, as several mentioned here, while liveness threshold is 30 seconds (6 * 5 seconds), the restart time could be minutes as it goes over all WAL etc.
So we end up with prometheus down for 5 minutes for example while it could only be down for 30 seconds.
For my case startup probe is irrelevant.

Could you reconsider adding this fix? if not, could you statically change the probe to higher retries count ?

**Comment by paulfantom** [comment]
> The point is, as several mentioned here, while liveness threshold is 30 seconds (6 * 5 seconds), the restart time could be minutes as it goes over all WAL etc.
So we end up with prometheus down for 5 minutes for example while it could only be down for 30 seconds.

If prometheus is replaying WAL, it is effectively down (not scraping data).

> For my case startup probe is irrelevant.

Most problems with prometheus and livenessProbe are due to WAL replay on prometheus start causing slow start. This is exactly what startupProbe was designed to handle.

**Comment by inoam** [comment]
@paulfantom I probably did not explain myself correctly, as startup probe will not help my issue at all.
> If prometheus is replaying WAL, it is effectively down (not scraping data). 

I totally agree!
My problem is that due to some load in the cluster, prometheus stopped responding for lets say 35 seconds, and since it is taken down because of the probe, it will start replaying data which will take some other minutes. 
Even if there was startup probe, I would not like to get to this position at all. 
What I want is top avoid unnecessary restart + WAL replay, which even upon "first time successful start", would cause much longer prometheus downtime, than it would have if it would not have gone down at all.
Increasing the livenessRetries will cause down time of lets say 1 minutes instead of 5.

**Comment by paulfantom** [comment]
We removed livenessProbe in https://github.com/prometheus-operator/prometheus-operator/pull/3502 which renders this PR not necessary anymore.

**Pull request closed without merging**
