### PR TITLE
Fix architecture image URL

### PR DESCRIPTION
**Pull request by supreeth7**
## Description
This PR intends to fix an invalid URL in the docs that points to the architecture image.

## Type of change
_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry
```release-note
Fix an invalid URL in the getting-started docs that points to the right architecture image
```

### CODE REVIEW

**Review by fpetkovski — APPROVED** [review]
Thanks!

**Comment by fpetkovski** [comment]
Hm looks like CI does not like the change

**Comment by slashpai** [comment]
It will be displayed correctly in https://prometheus-operator.dev/docs/user-guides/getting-started/

**Comment by supreeth7** [comment]
Thanks for confirming, I see that these docs leverage relative paths as the target audience view is the official documentation website rather than via GitHub.

**Comment by supreeth7** [comment]
Closing this PR on that note.

**Pull request closed without merging**
