### PR TITLE
Documentation: use the correct version in Documentation files

### PR DESCRIPTION
**Pull request by fpetkovski**
## Description

Fixes the version label used in Kubernetes resources that are part of the documentation.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Comment by paulfantom** [comment]
Let's put this on `main` branch. I don't think this is worth porting into `release-0.52`.

**Comment by fpetkovski** [comment]
I was thinking it might be better to merge to release-0.52 first because we still have to merge release-0.52 to main.

**Comment by paulfantom** [comment]
Ah, I thought this was already done. Ok, then this is fine to have on `release-0.52`

**Review by paulfantom — APPROVED** [review]
:shipit: lgtm

**Pull request merged**
