### PR TITLE
Fix proxyConnectHeader type in ScrapeConfig

### PR DESCRIPTION
**Pull request by dongjiang1989**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Fix proxyConnectHeader type in ScrapeConfig

fixes: #6523 

link: #6527 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Fix proxyConnectHeader type in ScrapeConfig
```

### CODE REVIEW

**Comment by dongjiang1989** [comment]
cc @slashpai @simonpasquier  PTAL

**Review by slashpai — APPROVED** [review]

**Comment by simonpasquier** [comment]
Thanks for fixing it! After more thinking I realize that we misrepresented the `ProxyConnectHeader` field.

Prometheus config says that it's a `map[string][]string` while the CRD field is equivalent to a `map[string]string`. Given that ScrapeConfig is v1alpha1 and that ProxyConnectHeader has a niche usage, I'd be inclined to "fix" the CRD now but it has to wait for the next minor release.

@prometheus-operator/prometheus-operator-reviewers thoughts?

**Comment by dongjiang1989** [comment]
If the CRD field changes from `map[string]string` to `map[string][]string`, this is a breaking change and will cause existing functionality to not work. 

Waiting for the next minor release. +1

**Comment by slashpai** [comment]
Since we are not doing it for patch release I am closing this one since you have already opened another PR https://github.com/prometheus-operator/prometheus-operator/pull/6541

**Comment by dongjiang1989** [comment]
> Since we are not doing it for patch release I am closing this one since you have already opened another PR #6541

Thanks

**Pull request closed without merging**
