### PR TITLE
WIP: include operator version in CRD annotations

### PR DESCRIPTION
**Pull request by paulfantom**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Resurrecting and fixing #4344.

Since CRDs are global and there can be more than one operator working in a cluster it would be good to have a way to verify if CRD in a cluster is compatible with the operator and vice versa. To do this I propose to include the operator version in CRD annotation.

Sadly controller-gen does not support injecting custom annotations in CRD metadata, hence the proposed solution includes post-generation CRD modification using `sed` (there might be a way to do this with `jq`, but I didn't manage to make this work).

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Include operator version in CRD annotations
```

### CODE REVIEW

**Review by fpetkovski — APPROVED** [review]

**Comment by fpetkovski** [comment]
Hm, looks like the CI is failing on Mac OS

**Comment by paulfantom** [comment]
ah, MacOS and `sed -i` doesn't work :facepalm:

**Comment by rexagod** [comment]
Fixes #4344.

(GitHub didn't pick up on the `Resurrecting and fixing https://github.com/prometheus-operator/prometheus-operator/issues/4344` string initially, so triggering again).

**Comment by rexagod** [comment]
@paulfantom It seems GitHub didn't pick up on `Resurrecting and fixing #4344.`, can you do "Fixes #4344" so that this is linked back to the original issue?

**Comment by rexagod** [comment]
It seems GitHub didn't pick up on `Resurrecting and fixing #4344.`, "Fixes #4344" should do the trick and hopefully link back to the original issue.

**Pull request closed without merging**
