### PR TITLE
Use appropriate HTTP scheme in Prometheus sidecars

### PR DESCRIPTION
**Pull request by fpetkovski**
## Description

When Prometheus is configured to serve HTTPS traffic, the thanos sidecar
and config reloader still try to reach Prometheus on HTTP.

This commit adjusts the Prometheus URL in both sidecards to match the
Prometheus URI scheme.

Fixes https://github.com/prometheus-operator/prometheus-operator/issues/4273

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

```release-note
Use the appropriate URI scheme in Prometheus sidecars when web tls is enabled for Prometheus.
```

### CODE REVIEW

**Review by PhilipGough — COMMENTED** [review]
lgtm, although do we want to get a unit test into https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/prometheus/statefulset_test.go#L432 or elsewhere?

**Comment by fpetkovski** [comment]
Good idea, extended the unit test with additional assertions.

**Review by PhilipGough — APPROVED** [review]
lgtm

**Review by simonpasquier — APPROVED** [review]
lgtm, will merge on green

**Pull request merged**
