### PR TITLE
chore: bump Kubernetes dependencies to v1.26

### PR DESCRIPTION
**Pull request by simonpasquier**
## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [X] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Comment by simonpasquier** [comment]
I suspect that we need to wait for https://github.com/kubernetes/kubernetes/pull/114617 and the next 1.26 patch release of k/k.

**Comment by simonpasquier** [comment]
https://github.com/kubernetes/kubernetes/pull/114617 has merged. According to https://kubernetes.io/releases/patch-releases/, k/k v1.26.1 is slated for Jan 18th (earliest).

**Comment by simonpasquier** [comment]
now ready for review!

**Review by PhilipGough — APPROVED** [review]
lgtm

**Pull request merged**
