### PR TITLE
jsonnet: create a monitoring mixin for prometheus-operator

### PR DESCRIPTION
**Pull request by paulfantom**
Convert
https://github.com/coreos/kube-prometheus/blob/master/jsonnet/kube-prometheus/alerts/prometheus-operator.libsonnet
into a prometheus-operator monitoring mixin

If we want this, I will add some tooling to make it testable.

/cc @coreos/team-monitoring

### CODE REVIEW

**Comment by lilic** [comment]
Come to think about it we already have kube-prometheus, which we need to bump anyways with each release of prometheus operator so not sure what problem this would solve besides introducing another dependency for users. Happy to convinced otherwise if there are benefits.

**Comment by paulfantom** [comment]
It is not about us, but about the broader community. Not everyone is using kube-prometheus.

**Comment by lilic** [comment]
But they can use the mixin in the same way no from kube-prometheus as well as from prometheus operator?

**Comment by simonpasquier** [comment]
One advantage I see having the mixin in the operator repository is that it's easier to keep in sync with the operator code (e.g. when you add a new metric, you can add the alert).

**Comment by brancz** [comment]
Right now kube-prometheus and prometheus-operator are often viewed as the same project, so I don't really mind this, but I also don't think it's very important right now. Once https://github.com/coreos/prometheus-operator/issues/3273 is done, we should certainly move ahead with this, but I think it might be more productive to focus on that first.

**Comment by paulfantom** [comment]
Updated to conform to [monitoring mixins guidelines](https://monitoring.mixins.dev/#guidelines-for-alert-names-labels-and-annotations).

Changed directory structure to align with other mixins.

Added `examples/mixin/alerts.yaml` target to Makefile. Now alerts are regenerated with every `make generate` execution. This allows for the basic jsonnet code evaluation test.

This is no longer WIP and all blockers were removed. Ready for review.

**Comment by s-urbaniak** [comment]
lgtm, we should just make sure these are also sourced in kube-prometheus, aka the place we migrated it from.

**Pull request merged**
