### PR TITLE
Fix panic when collecting metrics from Prometheus Agent controller

### LINKED ISSUE #5508: Operator v0.64.0 got panic after creating the CRD PrometheusAgent
**What happened?**

```
panic: interface conversion: interface {} is *v1alpha1.PrometheusAgent, not *v1.Prometheus                                                                                                                                                     
                                                                                                                                                                                                                                               
goroutine 678 [running]:                                                                                                                                                                                                                       
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*Collector).Collect(0xc0007bd548, 0xc000751768?)                                                                                                                            
    /home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/collector.go:69 +0xfc                                                                                                                                             
github.com/prometheus/client_golang/prometheus.(*wrappingCollector).Collect.func1()                                                                                                                                                            
    /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/wrap.go:131 +0x2e                                                                                                                                           
created by github.com/prometheus/client_golang/prometheus.(*wrappingCollector).Collect                                                                                                                                                         
    /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/wrap.go:130 +0x8d
```

**Did you expect to see something different?**

No panic.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create Prometheus agent by applying CRD `PrometheusAgent`.
2. Check the provisioned statefulset `prom-agent-<name>`.
3. A few seconds later, the `prometheus-operator` crashed.

**Environment**

* Prometheus Operator version:

`quay.io/prometheus-operator/prometheus-operator:v0.64.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:22:09Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.6-eks-48e63af", GitCommit:"9f22d4ae876173884749c0701f01340879ab3f95", GitTreeState:"clean", BuildDate:"2023-01-24T19:19:02Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

AWS EKS with EKS managed node groups.

* Manifests:

- CRD `PrometheusAgent`:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: test
  namespace: monitoring
spec:
  paused: false
  serviceAccountName: prometheus
  replicas: 1
  version: v2.43.0
  enableFeatures: []
  storage: {}
  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 200m
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  storage:
    ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          storageClassName: gp3
          resources:
            requests:
              storage: 1Gi
  scrapeInterval: 30s
  scrapeTimeout: 10s
  replicaExternalLabelName: __replica__
  externalLabels:
    cluster: my-cluster
  remoteWrite: []
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  probeSelector: {}
  probeNamespaceSelector: {}
```

- `prometheus-operator` args:

```
--log-level=debug                                                                                                                                                                                                                        
--kubelet-service=kube-system/kube-prometheus-stack-kubelet                                                                                                                                                                              
--localhost=127.0.0.1                                                                                                                                                                                                                    
--prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.64.0                                                                                                                                              
--config-reloader-cpu-request=200m                                                                                                                                                                                                       
--config-reloader-cpu-limit=200m                                                                                                                                                                                                         
--config-reloader-memory-request=50Mi                                                                                                                                                                                                    
--config-reloader-memory-limit=50Mi                                                                                                                                                                                                      
--thanos-default-base-image=quay.io/thanos/thanos:v0.30.2                                                                                                                                                                                
--web.enable-tls=true                                                                                                                                                                                                                    
--web.cert-file=/cert/tls.crt                                                                                                                                                                                                            
--web.key-file=/cert/tls.key                                                                                                                                                                                                             
--web.listen-address=:10250                                                                                                                                                                                                              
--web.tls-min-version=VersionTLS13
```

* Prometheus Operator Logs:

```
level=debug ts=2023-04-18T09:57:49.238252782Z caller=operator.go:611 component=prometheusagentoperator key=monitoring/test statefulset=prom-agent-test shard=0 msg="new statefulset generation inputs match current, skipping any actions"   
level=info ts=2023-04-18T09:57:49.238448063Z caller=operator.go:817 component=prometheusagentoperator key=monitoring/test msg="update prometheus status"                                                                                      
level=debug ts=2023-04-18T09:57:49.248057716Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="GET https://172.20.0.1:443/api/v1/namespaces/monitoring/pods?labelSelector=app.kubernetes.io%2Finstance%3Dtest%2Capp.kubernetes.i
level=debug ts=2023-04-18T09:57:49.307702761Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="PUT https://172.20.0.1:443/apis/monitoring.coreos.com/v1alpha1/namespaces/monitoring/prometheusagents/test/status 200 OK in 58 mi
level=warn ts=2023-04-18T09:57:49.30836959Z caller=klog.go:96 component=k8s_client_runtime func=Warning msg="unknown field \"spec.storage.ephemeral.volumeClaimTemplate.metadata.creationTimestamp\""                                          
panic: interface conversion: interface {} is *v1alpha1.PrometheusAgent, not *v1.Prometheus                                                                                                                                                     
                                                                                                                                                                                                                                               
goroutine 675 [running]:                                                                                                                                                                                                                       
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*Collector).Collect(0xc0001a8b40, 0xc00056ff68?)                                                                                                                            
    /home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/collector.go:69 +0xfc                                                                                                                                             
github.com/prometheus/client_golang/prometheus.(*wrappingCollector).Collect.func1()                                                                                                                                                            
    /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/wrap.go:131 +0x2e                                                                                                                                           
created by github.com/prometheus/client_golang/prometheus.(*wrappingCollector).Collect                                                                                                                                                         
    /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/wrap.go:130 +0x8d
```

### PR DESCRIPTION
**Pull request by ArthurSens**
## Description

Fixes #5508 

Just waiting for confirmation in case the mentioned new label is really needed 🤔 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [X] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
Fix panic when collecting metrics from agent controller
```

### CODE REVIEW

**Comment by simonpasquier** [comment]
lgtm. Have you checked that it fixes the issue? I guess we also need an e2e test that scrapes metrics from the operator :)
Can you submit the PR against the release-0.64 branch? I'll cut a 0.64.1 release.

**Comment by PhilipGough** [comment]
Looks good but would also like to see an e2e test

**Comment by slashpai** [comment]
Can we add https://github.com/prometheus-operator/prometheus-operator/pull/5476 also in patch to avoid alerting when crd not installed? I am working on changes

**Comment by ArthurSens** [comment]
Agreed that an e2e would be great here, but I'm struggling to do so to be honest 😓 https://github.com/prometheus-operator/prometheus-operator/pull/5471

**Comment by ArthurSens** [comment]
Manual tests worked though 

image

**Comment by simonpasquier** [comment]
@slashpai I'm afraid that the change won't apply cleanly on the release-0.64 branch because of #5472

**Comment by simonpasquier** [comment]
> Manual tests worked tho
> 
> image

I assume that you've checked `prometheus_operator_spec_replicas` too?

**Comment by ArthurSens** [comment]
> > Manual tests worked tho
> > image
> 
> I assume that you've checked `prometheus_operator_spec_replicas` too?

I did not, just one sec 😛

**Comment by ArthurSens** [comment]
Yeah, all good!

image


Tested with prometheus and prometheus agent running at the same time

**Review by PhilipGough — APPROVED** [review]

**Comment by ArthurSens** [comment]
Rebased on top of `release-0.64`, I'm not sure I have the permissions to change the PR target branch though

**Comment by simonpasquier** [comment]
> I'm not sure I have the permissions to change the PR target branch though

As the author, you should see the Edit button at the top

**Comment by ArthurSens** [comment]
> > I'm not sure I have the permissions to change the PR target branch though
> 
> As the author, you should see the Edit button at the top of the page.

TIL!

**Review by simonpasquier — APPROVED** [review]

**Pull request merged**
