### PR TITLE
Add support for opsgenie_api_key_file in the global Alertmanager configuration 

### LINKED ISSUE #4660: Add support for `opsgenie_api_key_file` in the global Alertmanager configuration
**What is missing?**

Alertmanager v0.24 (to be released soon) supports `opsgenie_api_key_file` in the global Alertmanager configuration. The internal configuration struct needs to be updated:

https://github.com/prometheus-operator/prometheus-operator/blob/f49dc4bb80e33f0044df4915ab4e844feb30c02e/pkg/alertmanager/types.go#L39-L66

**Why do we need it?**

Feature parity.

**Environment**

* Prometheus Operator version: N/A

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by mikechengwei**
## Description
Close #4660.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Comment by simonpasquier** [comment]
Thanks for starting this! You need a test to discard the field if the version is < v0.24.0 like we do in other places ([example](https://github.com/prometheus-operator/prometheus-operator/blob/f49dc4bb80e33f0044df4915ab4e844feb30c02e/pkg/alertmanager/amcfg.go#L1317-L1321)).

**Comment by mikechengwei** [comment]
@simonpasquier please help me review it agagin.

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by simonpasquier** [comment]
thanks!

**Pull request merged**
