### PR TITLE
chore: adding golden files support on admission tests

### PR DESCRIPTION
**Pull request by nicolastakashi**
## Description

I'm adding golden file supports on `admission` package, solves #5738

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [X] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
adding golden file supports on `admission` package
```

### CODE REVIEW

**Comment by ArthurSens** [comment]
While reading the [go docs](https://pkg.go.dev/gotest.tools/v3/golden) of this library, I can see that `golden.Get` does not update golden files even if we pass the -update flag. I believe we need to refactor those tests so we can use, [Assert](https://pkg.go.dev/gotest.tools/v3/golden#Assert), [AssertBytes](https://pkg.go.dev/gotest.tools/v3/golden#AssertBytes), [Bytes](https://pkg.go.dev/gotest.tools/v3/golden#Bytes) or [String](https://pkg.go.dev/gotest.tools/v3/golden#String)

**Comment by simonpasquier** [comment]
> While reading the [go docs](https://pkg.go.dev/gotest.tools/v3/golden) of this library, I can see that `golden.Get` does not update golden files even if we pass the `-update` flag. I believe we need to refactor those tests so we can use, [Assert](https://pkg.go.dev/gotest.tools/v3/golden#Assert), [AssertBytes](https://pkg.go.dev/gotest.tools/v3/golden#AssertBytes), [Bytes](https://pkg.go.dev/gotest.tools/v3/golden#Bytes) or [String](https://pkg.go.dev/gotest.tools/v3/golden#String)

I think that it's ok here because we use golden files for storing input data, not the expected output.

**Review by simonpasquier — APPROVED** [review]
LGTM but I'll let the final word to @ArthurSens

**Review by ArthurSens — APPROVED** [review]
> I think that it's ok here because we use golden files for storing input data, not the expected output.

Ooooh good point! Could we add a comment about this on the code? I'm 100% sure I'll forget about this eventually 😅

**Comment by simonpasquier** [comment]
Maybe the comment should go to https://github.com/prometheus-operator/prometheus-operator/blob/main/CONTRIBUTING.md#contribution-flow?

**Comment by nicolastakashi** [comment]
> Maybe the comment should go to https://github.com/prometheus-operator/prometheus-operator/blob/main/CONTRIBUTING.md#contribution-flow?

I'm not exactly what comment we should add, but on the fist PR I sent including golden files, we add a line talking about the golden files.

Maybe worth in another PR improve the documentation about testing.

**Comment by simonpasquier** [comment]
@nicolastakashi I was referring to @ArthurSens's remark about adding a comment for `golden.Get()` and indeed suggested to have the comment next to the mention of the golden files in the contributing doc.
Personally I'm fine with the PR in the current state and not sure that we need to add something to the contributing guide. Let's merge it and if Arthur has a good suggestion then we can have a follow-up PR ;)

**Pull request merged**
