### PR TITLE
fix: typo on AuthenticationMethod check

### PR DESCRIPTION
**Pull request by micborens**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

A typo bug has been introduced in this [PR](https://github.com/prometheus-operator/prometheus-operator/pull/6078/files) at the authentication method check. 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._
Fix typo on AzureSDConfig when authentication method is `ManagedIdentity`

- Fix AzureSDConfig authentication method ManagedIdentity

```release-note

```

### CODE REVIEW

**Review by slashpai — APPROVED** [review]
Thank you for reporting the issue and fix :)

**Comment by slashpai** [comment]
would you be able to add test also in https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/prometheus/resource_selector_test.go#L1782-L1848?

**Comment by micborens** [comment]
> would you be able to add test also in https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/prometheus/resource_selector_test.go#L1782-L1848?

I've committed a test

**Comment by simonpasquier** [comment]
If you open the PR against release-0.71, I'll be able to cut a patch release.

**Comment by micborens** [comment]
@simonpasquier I forked with on main branch 🤦 , I will close this PR, refork the repo, re-open a PR based on your release 0.71.
Thx 🙏

**Comment by micborens** [comment]
here is the new PR https://github.com/prometheus-operator/prometheus-operator/pull/6259

**Pull request closed without merging**
