### PR TITLE
Feat: Implemented Github Action linter

### LINKED ISSUE #7094: Implement GitHub action linter
### Component(s)

_No response_

### What is missing? Please describe.

Preventing issues like https://github.com/prometheus-operator/prometheus-operator/pull/7093

https://github.com/rhysd/actionlint

### Describe alternatives you've considered.

_No response_

## Environment
Kubernetes Version:
Prometheus-Operator Version:

### PR DESCRIPTION
**Pull request by slashexx**
## Description

This PR introduces a GitHub Actions workflow to lint the repository using `actionlint`, a tool designed to detect errors in GitHub Actions workflows. The workflow is integrated into the CI pipeline..

Fixes #7094 

## Type of change

What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that applies.

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

This change has been tested by running the `actionlint` tool locally and confirming that the workflow is properly linting the GitHub Actions files without errors. The CI pipeline runs successfully and reports any issues found during the linting process. No existing functionality has been broken by this change, as it only adds a new validation step to the CI pipeline.

## Changelog entry

Add GitHub Actions workflow to lint GitHub Actions YAML files with `actionlint`.

```release-note
Add GitHub Actions workflow to lint workflow files using actionlint.

### CODE REVIEW

**Review by slashpai — COMMENTED** [review]
Thank you for working on this, just a few nits :)

Also should we use https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions instead of downloading directly and using it?

**Comment by slashexx** [comment]
> Thank you for working on this, just a few nits :)
> 
> Also should we use https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions instead of downloading directly and using it?

Sure thing, on it !

**Comment by slashexx** [comment]
@slashpai I've made the required changes, please review :D

**Comment by slashexx** [comment]
> Nice, I think lint started working and it shows failures can you take a look

On it !

**Comment by slashexx** [comment]
@slashpai I've made the required changes

**Review by simonpasquier — DISMISSED** [review]
thanks!

**Review by slashpai — APPROVED** [review]

**Comment by slashpai** [comment]
hold

I think changed-files is messed up after update as it is not giving proper output

**Review by slashpai — CHANGES_REQUESTED** [review]
We need to fix the changed files actions before merging

**Comment by slashexx** [comment]
> We need to fix the changed files actions before merging

I'll look into it.

**Comment by slashexx** [comment]
The outputs fine now, I guess. @slashpai can you confirm ?

**Comment by slashexx** [comment]
@slashpai it says you requested for some changes ? Can I confirm if there are any other changes than the changed-files.yaml or is this PR good to go ?

**Review by slashpai — APPROVED** [review]

**Comment by slashpai** [comment]
Thanks for working on this :)

**Comment by slashexx** [comment]
> Thanks for working on this :)

Happy to help  !

Also, I'd love to contribute more around here, can you suggest a good starting point and maybe the prerequisites as well ?

**Pull request merged**
