### PR TITLE
Shards and Replicas document

### LINKED ISSUE #3795: Documentation and examples around shards and replication support in the operator
Hi 
Can you please refresh the documentation around sharding support and prometheus replication? 

Thanks
Niki Dokovski

### PR DESCRIPTION
**Pull request by mikechengwei**
Fix #3795 
**Release Note Template (will be copied)**

```release-note:REPLACEME
Add shards and replicas document.
```

### CODE REVIEW

**Comment by nicolastakashi** [comment]
@mikechengwei it could be nice if you can provide some examples about resharding

**Comment by mikechengwei** [comment]
ok.

**Comment by mikechengwei** [comment]
@simonpasquier  Hi, can you have a look？

**Comment by mikechengwei** [comment]
Since I don’t have permission for this pr, I’ll create a new pr #4358.

**Pull request closed without merging**
